### ISSUE TITLE
image jump

### ISSUE THREAD

**Issue by akiyatkin** [andreknieriem/simplelightbox#1]
Hi, I tried your script!
When flipping the image. Hides picture twitches. Before full of hidden again briefly shown.
(Win8, Chrome)

Привет, пробовал твой скрипт!
Когда листаешь картинки. Скрываемая картинка дёргается. Перед полным скрытием снова на мгновение показывается.

**Comment by andreknieriem** [comment]
Hi, can you tell me, when this happens, in which browser and on which device?

**Comment by akiyatkin** [comment]
When listing images, Chrome,  Notebook Windows 8

**Comment by andreknieriem** [comment]
Hey akiyatin, you closed the issue? Was that right?

**Comment by akiyatkin** [comment]
I just wanted to help and report bugs. Then I removed the script, and I have nothing to add!

Since I have no more information, and you're asking, I decided to close the issue.

**Comment by bzvyagintsev** [comment]
Have the same issue on my website.

**Comment by andreknieriem** [comment]
Hello, is this error on the grid of the thumbnails? Because that has nothing to do with the plugin, it's just some Demo Markup.

**Comment by bzvyagintsev** [comment]
I make my own grid.
I test website today on android device, and it works fine.

But on desktop, when I click "next", image slide, and before new image load, plugin show previous image.

I can give you link to my website and you can take a look. Can i do it here?)

**Comment by andreknieriem** [comment]
Hi, yes please share a link.

**Comment by bzvyagintsev** [comment]
http://xn--90aftjhof4g.xn--p1ai/products/c-02

you can see images with your plugin on the bottom in section "Дополнительные фото"

**Comment by bzvyagintsev** [comment]
I discovered that this issue appers only on ubuntu in chrome beta version.
On windows stable chrome and android chrome it works perfect!

**Comment by andreknieriem** [comment]
Hey, ok its strange, but it works in old IE's, so I think the beta has a bug, not my script.

**Comment by bzvyagintsev** [comment]
My android get a new version of chrome, and It has the same issue now))
