### ISSUE TITLE
Not working properly on windows 8.1 phone

### ISSUE THREAD

**Issue by mnakalay** [andreknieriem/simplelightbox#10]
Hello I just wanted to let you know that on a Windows 8.1 phone the gallery is not working properly.

When clicking on a thumbnail it just follows the link and opens the image in a new page instead of opening the lightbox.

**Comment by andreknieriem** [comment]
Hello mnakalay, thanks for your feedback. I cannot reproduce you error. Here is an image of windows phone 8.1.
![imag1145](https://cloud.githubusercontent.com/assets/4500367/11034583/efa0b7f8-86ec-11e5-8c56-8a6c26ecf581.jpg)
