### ISSUE TITLE
captions not showing

### ISSUE THREAD

**Issue by duncanhotston** [andreknieriem/simplelightbox#102]
I have a  problem with the captions not showing on my image popups. When Wordpress updates to latest version the captions disappeared and only show the default 'Item 2 of 82' etc.
Can you take a look and tell me what has gone wrong?

https://microplasmouldings.com/mpm-brands/sperm-keyrings/  click on Standard colours tab

thanks

**Comment by andreknieriem** [comment]
* Not reproducable
