### ISSUE TITLE
body {padding-right: 15px;} when opening image

### ISSUE THREAD

**Issue by Mrbrand** [andreknieriem/simplelightbox#11]
Hi,

Somehow, when opening an image, css for body is changed (padding-right: 15px;). 
This makes the site flicker slightly to the left. Is it possible to disable this?

Thanx for this great plugin.

**Comment by Mrbrand** [comment]
I managed to find a workaround by disabling this line: 
//if(options.disableScroll) handleScrollbar('hide');

**Comment by andreknieriem** [comment]
Hi, can you tell me which browser you use? This is a problem with the scrollbar disable option. You can call the plugin with the Option disableScroll: false; no need for change on Sourcecode.

**Comment by Mrbrand** [comment]
I use chrome. Thank you for the tip about the scroll option. Works perfectly now.

**Comment by andreknieriem** [comment]
Hey, but the 15px on body should only appear, if there is a scrollbar, not without. Are you using, windows, linux or mac?

**Comment by Mrbrand** [comment]
Linux ubuntu with chrome.

**Comment by andreknieriem** [comment]
Hi, I've just tested it on ubuntu in chrome and firefox and cannot see an error. The 15px goes to the body, but at the same time, the scrollbar disappers and so everything is just fine.

**Comment by AlexByte** [comment]
@andreknieriem It changes layout, when body width is limited.
