### ISSUE TITLE
Request for new features

### ISSUE THREAD

**Issue by andrconstruction** [andreknieriem/simplelightbox#110]
Hello Andre. Thank you for your programm.
Will you implement some pritty functions like zoom and rotate? At the moment when I try zoom a picture via browser ( Ctrl+Scroll), it doesn't changed? 

Have you any donate methods except the paypal? I want make a little donate.

**Comment by andreknieriem** [comment]
Hey, yes this feature is my mind along with pinch to zoom feature. Its a hard feature. For now I only have paypal donations. But you can send me an email on my website a I can give some information how to donate. 

Thanks!

**Comment by andrconstruction** [comment]
Can't email you


Final-Recipient: rfc822; info@andreknieriem.de
Original-Recipient: rfc822;info@andreknieriem.de
Action: failed
Status: 5.7.1
Remote-MTA: dns; andreknieriem.de
Diagnostic-Code: smtp; 554 5.7.1 <info@andreknieriem.de>: Relay access denied

**Comment by andreknieriem** [comment]
Yes, its info@andrerinas.de or simple andreknieriem@gmail.com.

**Comment by andreknieriem** [comment]
Hi. The Zoom Feature is enabled. Rotate will be the next thing ;)

**Comment by andrconstruction** [comment]
Hi that's cool news, will this feature accessed for desktops?

**Comment by andrconstruction** [comment]
O cool, the zoom implemented . Many thanks

**Comment by andreknieriem** [comment]
Rotating will not be implemented.

**Comment by andrconstruction** [comment]
is never?
