### ISSUE TITLE
Auto show first image?

### ISSUE THREAD

**Issue by nikolakurtic** [andreknieriem/simplelightbox#116]
Is there a way to auto show first image upon a page load?
I tried $gallery.show() and $gallery.next() just after
var $gallery = $('.gallery a').simpleLightbox();
in demo/index.html

Thanks!

**Comment by andreknieriem** [comment]
Hi there, it works with:

var $gallery = $('.gallery a').simpleLightbox();
$gallery.open().

Best regards
