### ISSUE TITLE
SimpleLightBox with OwlCarousel

### ISSUE THREAD

**Issue by minamoto19** [andreknieriem/simplelightbox#117]
Hello.

First of all I want to congratulate you on this absolutely exceptional lightbox.
I've been looking very much for that kind of dead simple and lightweight lightbox plugin that works out of the box and easily customizable.

I've been using it over owl carousel which cloning the images a few time to make a loop illusion.
The outcome with SimpleLightBox is showing each image three times in the lightbox.

Any solution to this?

**Comment by andreknieriem** [comment]
Hey,

just use another selector. Something like $('.owl-item').not('.cloned').simpleLightbox(). This should work

**Comment by minamoto19** [comment]
Hello.

Thanks for the help. .not('.cloned') worked.
I wanted to open the lightbox from a button not the actual image so:

My HTML mark up 

```
<div class="product-carousel owl-carousel">
  <div class="product-img">
    <a href="uploads/product/pr-15.jpg" class="dm-imgbox enlarge">&plus;</a>
    <img src="uploads/product/pr-15.jpg" alt="">
  </div>
  <div class="product-img">
  <a href="uploads/product/pr-16.jpg" class="dm-imgbox enlarge">&plus;</a>
  <img src="uploads/product/pr-16.jpg" alt="">
  </div>
</div>
```

And my Javascript became:
```
  $('.owl-item').not('.cloned').find('.dm-imgbox').simpleLightbox({
    showCounter: true,
    captions: false
  });
```


Thanks again
