### ISSUE TITLE
Does not work with custom port in image link

### ISSUE THREAD

**Issue by and-hom** [andreknieriem/simplelightbox#118]
If image is loaded for url with custom port, lightbox does not work. Link is working as regular link

How to reproduce:
1. Take an example
2. Replace image links to external, for example, this one http://wwmap.ru:7007/spot/0/img/40057 (this is a code fragment from original demo)
```
	<div class="container">
		<h1 class="align-center">Simple Lightbox Demo Page</h1>
		<div class="gallery">
<!-- links are changed here!!! -->
			<a href="http://wwmap.ru:7007/spot/0/img/40057" class="big"><img src="http://wwmap.ru:7007/spot/0/img/40057/preview" alt="" title="Beautiful Image" /></a>


			<a href="images/image2.jpg"><img src="images/thumbs/thumb2.jpg" alt="" title=""/></a>
```
3. Now open page in browser (I use chromium Version 71.0.3578.80 (Official Build) Built on Ubuntu , running on Ubuntu 18.04 (64-bit) and Firefox 64.0+build3-0ubuntu0.18.04.1). If you click on first (modified) image it will be opened as regular link. If you click second image and then click left paging button, image willbe displayed correctly.

I have no problems with this behaveour in production usage, because images and site has same domain and port thanks to nginx. But is's quite annoying for development environment, where I use non-standard ports.

**Comment by andreknieriem** [comment]
Hi there, 
there an option to allow custom image links. Just set ` fileExt: false`

`$('.gallery a').simpleLightbox({
  fileExt: false		
});`
