### ISSUE TITLE
Hi, it it possible to set the order of images by adding an element to  the markup?  

### ISSUE THREAD

**Issue by maggsweb** [andreknieriem/simplelightbox#119]

**Comment by andreknieriem** [comment]
Hi, the order of the images in the lightbox, is the order in the markup. If you reorder the images in your markup, you have to reinitalize the lightbox.

**Comment by maggsweb** [comment]
My images are rendered across x number of columns (for layout purposes) but need to display horizontally (for the correct sequence) so re-ordering them in the markup is not an option for me.
Thanks anyway.
