### ISSUE TITLE
Disable Right/Left Shift Animation

### ISSUE THREAD

**Issue by lucas-sp** [andreknieriem/simplelightbox#12]
Is there an option to disable the animation between slides that makes the image shift right and left? I'd like the option of just having the fade in/out, but I'm hesitant to dig into the javascript myself. I'm a javascript novice, but can probably figure it out if someone could at least point me in the right direction. Thanks!

**Comment by andreknieriem** [comment]
Hey, now there is no feature for this but I will add it to the feature list. If you want to try it on your own take a look at the function slide.

**Comment by lucas-sp** [comment]
Okay, thanks. Lovely plugin, by the way!

**Comment by nicekiwi** [comment]
Made a pull request to support this. :tongue:

**Comment by andreknieriem** [comment]
Done in version 1.7.0, thanks nicekiwi for the pull request!
