### ISSUE TITLE
open an image via the hash pid

### ISSUE THREAD

**Issue by JeromeSpilmont** [andreknieriem/simplelightbox#120]
Hi Andre, first of all it's a sweet job ! 

Just a question is it possible to show an image directly via the #pid= ?

ex : http://localhost/pictures#pid=6 -> will show the sixth image of the gallery 

Regards

**Comment by andreknieriem** [comment]
Hi, for now it's not possible. But you try to do it yourself via open method with that pid.

**Comment by MijoBarbaric** [comment]
A pity simplelightbox doesn't allow opening the lightbox to a specific image...

Here is my workaround (using [HashGet](https://www.npmjs.com/package/hashget))

```javascript
  let $gallery = $(".gallery");

  $gallery.find("a").simpleLightbox();

  const locHash = new HashGet();

  let pidStr = locHash.getValue("pid");
  let isPidNumber = pidStr && !isNaN(pidStr);
  if (isPidNumber) {
    let pid = +pidStr; //Convert to number

    setTimeout(function() {
      //Open lightbox for specific image
      $gallery.find(`a:nth-child(${pid})`).click();
    }, 0);
  }
```
