### ISSUE TITLE
Links in Caption Help Wanted

### ISSUE THREAD

**Issue by quirkit** [andreknieriem/simplelightbox#121]
### HELP WANTED 
Hi, trying to create link from caption. Works on desktop but not tablets or mobiles. Any suggestions?

<div class="portfolio-item-caption"><a href="web-design.png" title="Visit site here &lt;a href=&quot; http://lilycot.co.uk&quot; target=&quot;_blank&quot;&gt;Lilycot Holiday Home &lt;/a&gt;" class="lightbox"></a> 

Thanks

**Comment by andreknieriem** [comment]
Hi, do you have a link? Don't get your problem ;)

**Comment by quirkit** [comment]
Hi again, any joy with looking at mobile and tablet links? Thanks

**Comment by andreknieriem** [comment]
Hi. Ok it is not working on mobile, because of the touch/drag events on the whole image with caption. It's not working for now. Sorry. I will try to make this work in the future.
