### ISSUE TITLE
Pinch to zoom is working incorrectly if the page is scrolled

### ISSUE THREAD

**Issue by slatinsky** [andreknieriem/simplelightbox#123]
First I want to thank you for making this awesome lightbox!

Issue:
If the page is scrolled, pinch to zoom zooms to incorrect part of the image. If the page is not scrolled, it works fine

How to reproduce:
1) Add 50x \<br\> tag below body tag in demo file index.html
2) Host it somewhere and open it in Chrome for Android

Tested on:
Android 8, Carbon Rom - Chrome browser for Android (71.0.3578.83), Xperia Z2
Android 5, CyanogenMod - Chrome browser for Android

Simple lightbox version 1.16.0

Video:
https://youtu.be/48B3Ph68noc

**Comment by andreknieriem** [comment]
Alright, can see the error. Will be fixed soon. Thank you!

**Comment by andreknieriem** [comment]
Fixed in new version ;)
