### ISSUE TITLE
Custom html class 

### ISSUE THREAD

**Issue by sashtown** [andreknieriem/simplelightbox#124]
Since there is none as a default it would be helpful having the option to set a custom class for the `<html>` element when the lightbox is applied:

```
htmlClass: 'has-lightbox'
```

**Comment by andreknieriem** [comment]
It's in 1.16.2 ;)

**Comment by sashtown** [comment]
Yay, excellent! 

(BTW: It would be cool to have [those options](https://github.com/andreknieriem/simplelightbox#javascript-options) listed in alphabetical order. 😎)

**Comment by andreknieriem** [comment]
Good idea ;)
