### ISSUE TITLE
How make a single image?

### ISSUE THREAD

**Issue by St182** [andreknieriem/simplelightbox#13]
Hello!
How make a single lightbox per one image, if many images on page?
Or make many galleries on one page?
Plugin create a gallery only.
Thx.

**Comment by St182** [comment]
I found a solution.
Different selectors for each gallery.
Example:
$ ('. cart-gallery-1 a'). simpleLightbox ();
$ ('. cart-gallery-2 a'). simpleLightbox ();
...

**Comment by andreknieriem** [comment]
I just wanted to write exactly what you have found ;) Have fun with the lightbox!
