### ISSUE TITLE
Double Click Not Zoom on browsers.

### ISSUE THREAD

**Issue by coderkan** [andreknieriem/simplelightbox#131]
Hi @andreknieriem, 

Thanks for your effort this is a very good project. 

I have runned your demo example and implemented to my project. I have wonder that when I double click on image preview, the picture can not zoom(both your demo and my implemented project) but when I open **developer tool** on browser it will work well. When open Dev Tools double clicking zoom images. 

**Double clicking** is a feature your project or not?

Have you any idea about it?

Regards
Erkan

**Comment by andreknieriem** [comment]
Hey, it is a fearure on mobile devices, not on desktop. If you open dev tools and can zoom you probably have mobile device emulation activated.

**Comment by coderkan** [comment]
Oh sorry :)

I have no idea on this feature. Thanks for your giving information. 
It can be a good feature on desktop :) 

Thanks a lot.

**Comment by andreknieriem** [comment]
No Problem and yes, this feature should go to desktop devices as well. Thanks ;)

**Comment by dobromir-hristov** [comment]
Yeah, what was the intention of not allowing it on browsers? I think double click to enable zooming is pretty intuitive, event if its up to 100% of image size.

**Comment by coderkan** [comment]
Hi @andreknieriem ,

I will try to implement double clicking zoom and pull request to you.

**Comment by andreknieriem** [comment]
Thanks to @coderkan it is now availabled.
