### ISSUE TITLE
Close cross not show under Edge

### ISSUE THREAD

**Issue by fredtempez** [andreknieriem/simplelightbox#133]
Hi,
You should remplace cross character by : `closeText:"&#10005;"`

**Comment by andreknieriem** [comment]
Hey, I cannot reproduce this error. Can you tell me, on which OS? Windows 10 or earlier?

**Comment by fredtempez** [comment]
Edge with W10 french language
Maybe UTF8 issue 
[`screencopy`](https://ibb.co/GpRy3RJ)
Changing closeText resolve issue

**Comment by andreknieriem** [comment]
Ok, I thanks. I see if this is working in every other browser and language ;)

**Comment by andreknieriem** [comment]
Should work now in 1.17.2
