### ISSUE TITLE
Is there any reason to use 'a' tag for openning the lightbox?

### ISSUE THREAD

**Issue by romansh** [andreknieriem/simplelightbox#134]
As I can there is some hardcoded part in simplelightbox sourcode

`return testExt && $( element ).prop( 'tagName' ).toLowerCase() == 'a' && ( new RegExp( '\.(' + options.fileExt + ')$', 'i' ) ).test( testExt );`

I'd not like to use 'a' in html because of SEO and so on, I prefer 'li'. So the question: is there any deep reason to use 'a' tag for open the lightbox and why is the HTML tag hardcoded?

That is almost the only reason to not use Simplelightbox :( It's really simple and convenient to use, but 'a' :)

The other one - there are not dotted navigation but this is not so important for me.

**Comment by andreknieriem** [comment]
Hey, no, there is no reason for that. It is a leftover from version 1.0. I will change this.

**Comment by andreknieriem** [comment]
Changed in the new version
