### ISSUE TITLE
Support for WebP Images Missing

### ISSUE THREAD

**Issue by Mohit2611** [andreknieriem/simplelightbox#135]
Hi,

I found that support for WebP images is missing and it opens the image URL. I have not tested other next gen images which Google would ideally recommend.

**Comment by Mtillmann** [comment]
please have a look at the `fileExt` option. At the moment it does not include webp but you can always expand the list when creating your instance.

**Comment by Mohit2611** [comment]
Thank you. Yes, it can be easily achieved by the `fileExt` option.

Though I would recommend to include all the latest image extensions in the build itself to keep the plugin at pace with the changing times.

Closing the issue.

**Comment by andreknieriem** [comment]
It's now in the newest version
