### ISSUE TITLE
Reorganize div

### ISSUE THREAD

**Issue by psd-web** [andreknieriem/simplelightbox#136]
Hi!

I'm using this plugin for a simple gallery, but in order to display it as my design, I need to organize it in this way:

- div sl-wrapper
- - button close
- - div spinner
- - div image
- - - img
- - - div counter
- - - - div caption
- - - - div navigation

I've been able to put caption and navigation inside counter, but I'm not able to puc counter div inside .sl-image  (after img).

Thanks

**Comment by Mtillmann** [comment]
Hi, could you kindly provide some example code of what you want to achieve? thanks!

**Comment by psd-web** [comment]
Hi!

I couldn't post some code here, sorry. But here is what I have: http://mixite.cat/demo/
What I need is to place div .sl-counter inside the div .sl-image

Thanks!!

**Comment by psd-web** [comment]
Hi, 
Anyone that could help me with this?
Thanks!!

**Comment by andreknieriem** [comment]
Ok I won't do this. Sorry
