### ISSUE TITLE
Go next image on image click

### ISSUE THREAD

**Issue by Erdem-Ozyalcin** [andreknieriem/simplelightbox#137]
Hi, 

I am trying to go to next image on image click.

I tried this example on. https://github.com/andreknieriem/simplelightbox/issues/64 But it doesn't work.

For me the solution was to edit the source code a little bit.
I added this on line 670. After the double click event.
`.on('click', function (e) {
	loadImage( 1 );
});`

**Comment by andreknieriem** [comment]
OK thanks for mentioning ;)
