### ISSUE TITLE
Add option for caption positioning

### ISSUE THREAD

**Issue by howi85555** [andreknieriem/simplelightbox#14]
Hi André, a nice feature would be an option to set the caption's position.
Currently, the caption is overlapping the image at the bottom of the image.
The option should allow to do position the caption below the image, such that the image is not covered by the caption at all. 

I guess, one more value 'top' for the option can be helpful for those people that want their caption to be positioned on top of the image instead of below.

So this all could end up in an option like
captionPosition: 'overlay'|'bottom'|'top'

Thanks in advance,
Holger

**Comment by andreknieriem** [comment]
Release is online. V1.6.0
