### ISSUE TITLE
cannot read property "tagName" of undefined

### ISSUE THREAD

**Issue by andrconstruction** [andreknieriem/simplelightbox#140]
hi Andre.
After upgrade to last version 1.17.2 I faced wtih an error :

cannot read property "tagName" of undefined,

 the chrome debugger point on 91 line 
**tagname = objects.get()[0].tagName,**

a calling script below 

$( 'a[rel="shadowbox"]' ).simpleLightbox( {
    alertError : false,
    captionPosition : 'outside',
    widthRatio : 0.9,
    closeText : '<span class="fa fa-times-circle text-info-light fa-2x"></span>',
    navText : ['<span class="fa fa-chevron-circle-left fa-2x text-info-light"></span>', '<span class="fa fa-chevron-circle-right fa-2x text-info-light"></span>']
} );

what do i do wrong?

**Comment by andrconstruction** [comment]
Tested with 1.17.1 the same error.
Last workiing version is 1.17.0

**Comment by andreknieriem** [comment]
And you did not change anything else? Cause https://github.com/andreknieriem/simplelightbox/commit/cecf53c36a5f34828360c53adaf5c2d217851aa8 has nothing to do with your error.

**Comment by Klenkes** [comment]
This error occurs if your simpleLightbox selector isn't present on the current page, like you load an external file with all your javascript calls.

In this case you have check for the selector first:
`if($('.images a').length){
  $('.images a').simpleLightbox();
}
`
Not elegant and not nice but it works.
