### ISSUE TITLE
Need help - Full Screen on Android

### ISSUE THREAD

**Issue by steffenle** [andreknieriem/simplelightbox#141]
Hello,
is it possible to place an button to go in Full Screen Mode on Android Mobile Phone with Firefox?
If I start the my gallery with simplelightbox the pictures are very small.

Regards
Steffen

**Comment by steffenle** [comment]
Screenshot:
![Screenshot_20190614-135808_Firefox](https://user-images.githubusercontent.com/35337319/59508150-40410480-8ead-11e9-98ea-0038fdf9c122.jpg)

**Comment by steffenle** [comment]
is not closed :-)

**Comment by andreknieriem** [comment]
You can also set the ratios from height and with to 1.0. Then it's like fullscreen and with pinch to zoom oder double click to zoom you can see more ;)
