### ISSUE TITLE
Overlay not working if multiple images present

### ISSUE THREAD

**Issue by gyan111** [andreknieriem/simplelightbox#142]
Hi,

If there is one image then the overlay is working but if there is multiple images then the overlay is not working and background is not visible. 

I have applied these setting.
`var lightbox = $('.image').simpleLightbox({
		  	  	sourceAttr:"src",
		  	  	overlay:true,
		  	  	nav:false,
		  	  	spinner:false,
		  	  	showCounter:false,
		  	  	loop:false
		  	  });`

**Comment by andreknieriem** [comment]
Do you have an example? Cannot reproduce

**Comment by andreknieriem** [comment]
Closed because of no answer
