### ISSUE TITLE
Image is turned on one side

### ISSUE THREAD

**Issue by RempadDesign** [andreknieriem/simplelightbox#143]
Hi,
We have a strange issue for some images. They are uploaded ok but in the lightbox they are showin on side. You can check the example of photo No.13 from this link: https://www.web22.ro/dev/floraria-crina/buchete-pentru-aniversari

Thank you in advance.

**Comment by Mtillmann** [comment]
Hello @RempadDesign ,

Maybe the issue is rather related to EXIF specs like 

https://stackoverflow.com/questions/42401203/chrome-image-exif-orienation-issue 

describes. 

Best

Martin
