### ISSUE TITLE
Show name of file under every image

### ISSUE THREAD

**Issue by gaiapuffo** [andreknieriem/simplelightbox#144]
Hi, when i create the gallery I have a list an image, but for see the name of the file I have to click on the image.
Is possible to show the name directly?

**Comment by andreknieriem** [comment]
Hey, I don't see an advantage on showing the filename in the caption. 
![image](https://user-images.githubusercontent.com/4500367/67092218-f5aefc00-f1ae-11e9-9a67-42936d8735f9.png) You can see it at the buttom in every browser.
