### ISSUE TITLE
Scrolling still possible when Lightbox is opened

### ISSUE THREAD

**Issue by city17** [andreknieriem/simplelightbox#145]
Hi, I noticed that scrolling is still possible when lightbox is opened (at least with Mac trackpad in Chrome or Firefox), even if I explicitly set it to disableScroll : true (which should be the standard anyway).

Is this a bug or am I missing something?

**Comment by stevehobbsPB** [comment]
Discovered the same issue... I fixed this by applying `overflow: hidden` to the html. When the modal is open it toggles the class `has-lightbox`.

`
html.has-lightbox {
    overflow: hidden;
}
`

👍

**Comment by city17** [comment]
Thanks Steve, that seems to solve it. The only issue I noticed with your solution is that it removes the scrollbar, resulting in the whole layout of the page expanding slightly to the right. Any idea how to prevent that?

**Comment by stevehobbsPB** [comment]
You'll likely need to apply some JavaScript to calculate the scroll bar width, and then use this to apply an offset to the html.

You should find this useful: This may be useful to you: https://muffinman.io/get-scrollbar-width-in-javascript/

**Comment by andreknieriem** [comment]
In which browser? This is exactly what the lightbox does. It adds overflow hidden to the body and a padding right with the width of a scrollbar. It works on my browsers without any problem.

**Comment by stevehobbsPB** [comment]
This occurs in Chrome, Safari and Firefox on Mac

**Comment by andreknieriem** [comment]
Is this still a problem?

**Comment by andreknieriem** [comment]
Closed due to no response

**Comment by sb-relaxt-at** [comment]
In my usage the problem is that only the body is set to overflow: hidden but not the html element (where the scrolling occurs in my case).
