### ISSUE TITLE
Help Wanted: How to make simplelightbox work with dinamically generated HTML?

### ISSUE THREAD

**Issue by wilmermurillo** [andreknieriem/simplelightbox#146]
Hi all,
I'm not exactly a dev so maybe this is a dumb question:

I'm using Dribbble API to bring images from my portfolio using simplelightbox, but for some reason it seems to not work with HTML that's generated dinamically by another JS library.

Here's my code:
```
jribbble.shots({token: "2f2ee1e92a2e3a82af8cc3e958831ef27cc0628be9e5da3784faccebe70fe424", per_page: 10}, function(shots) {
	document.querySelector(".dribbble-shots-list").innerHTML = shots.reduce(function(html, shot) {
	return html + '<div class="column column-block"><a class="d-shot" href="'+  shot.images.hidpi + '" target="_blank"><img src="' + shot.images.normal + '"></a></div>';
	}, "");
	});

var lightbox = $('.dribbble-shots-list a').simpleLightbox();
```

Thanks in advance for your help.

**Comment by andreknieriem** [comment]
Hey. You need to destroy the lightbox and reload it everytime. You can use the method refresh for this.
