### ISSUE TITLE
Slow Animation

### ISSUE THREAD

**Issue by AInteriorB** [andreknieriem/simplelightbox#147]
Hey there,

I'm wondering if I could speed up the animation when I zap through a gallery. I already decreased animationSpeed to a minimum but it still feels very slow: 
* image flies out to the left
* pause
* image flies in and fades in from the right

If you have a huge gallery and impatient visitors, this takes too long. Have you any suggestions what I can do? This was already mentioned by #91 . I can confirm, this lightbox is awesome but it would be great to have a faster transition.

**Comment by davidverweij** [comment]
Personally, I found the fade animations a tad slow. I *(really briefly)* tried to add a new settings variable called `fadeSpeed`, but instead went for a quick hack: overriding the speeds for all fades to near nothing - see below. Might inspire something similar.

```js
key: "fadeIn",
    value: function fadeIn(elements, duration, callback, display) {
      var _this10 = this;
      // overriding duration values (all seem to be 200 or 300)
      duration = 10;
      ...
```
Same applies for the 
```js
key: "fadeOut"
```
