### ISSUE TITLE
show vs open

### ISSUE THREAD

**Issue by TheRichCourt** [andreknieriem/simplelightbox#148]
Seems to be some confusion between `show` and `open` in the docs. I noticed it was changed a while back, so maybe it's a hangover from that.

If you look here: https://simplelightbox.com/#events the list contains an event called `show.simplelightbox`, which works fine. The example code below that list shows how to use an event called `open.simplelightbox`, which doesn't work.

The public method documented there is `.open()`, which I haven't tried, but might be adding to the confusion for some.

**Comment by andreknieriem** [comment]
Hey. Thanks, that was an error in the docs. The open event is right and working, but the open event was changed to show.
