### ISSUE TITLE
pinch/zoom not working on mobile

### ISSUE THREAD

**Issue by mattbra1155** [andreknieriem/simplelightbox#149]
Hello, 

I recently implemented your lightbox to a page (https://minus-architektura.pl/kategoria/projekty/). Everything works fine until I want to pinch/zoom on mobile the image when the lightbox is open. It just swipes to the next image and doesn't let me zoom in. Any ideas on what could be wrong?

Thanks|,
Matt

**Comment by andreknieriem** [comment]
If you are using the wordpress plugin  it is outdated. Please use the javascript script standalone, because I am not developing for Wordpress anymore. Best regards
