### ISSUE TITLE
Working example?

### ISSUE THREAD

**Issue by ottkaskjr** [andreknieriem/simplelightbox#150]
Hi!
Since I'm beginner in web development, can you provide a full working example with html elements including fully initialized jQuery block, the current instructions are very limited. At the moment I don't know if I should add the .gallery class to <div> element containing the <img> elements or should I add the class on every <a> element or just on <img> elements. 
Secondly it's unclear if the lightbox has default options enabled or should I add all the options manually. 
Thanks!

**Comment by ottkaskjr** [comment]
somehow my html elements were removed from the post since I used html brackets.. I will post that sentence again:"At the moment I don't know if I should add the .gallery class to "div" element containing the "a" elements or should I add the class on every "a" element or just on "img"  elements."

**Comment by andreknieriem** [comment]
Just download the code and look at the demo folder. There is a working example. And on simplelightbox.com too.
