### ISSUE TITLE
Question (Not a Issue)

### ISSUE THREAD

**Issue by Avloyp** [andreknieriem/simplelightbox#152]
Hey Andre or anybody who can help,

How do I make box with text when I or someone click on a picture?

Like you click on a picture then comes a box with text rather a bigger picture.

**Comment by YourSouLi5Mine** [comment]
You should use sweet alert instead

**Comment by Avloyp** [comment]
Sweet Alert?

**Comment by Mtillmann** [comment]
@Avloyp try this one: https://sweetalert2.github.io/

Please consider using some discord or subreddit for issues like this, thank you!
