### ISSUE TITLE
Clicking to close simple lightbox adds `padding-right` style to body element

### ISSUE THREAD

**Issue by cjholowatyj** [andreknieriem/simplelightbox#154]
On my installation, every time simple lightbox is closed by clicking on the `.sl-close` element an inline style is added to the `<body>` element increasing the right padding every time the lightbox is opened and subsequently closed.

So far I've discovered that it's an issue with how simplelightbox is calculating the size of the scrollbar... I'm trying to figure out how to disable the hidden scrollbar feature but still working on that... See gif for visualization of the issue.

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/33474672/66493786-a23cff80-ea84-11e9-8d65-c909d806ecde.gif)

**Comment by cjholowatyj** [comment]
Ok I've discovered the issue with my implementation...

Aside from changing disableScroll to false (disableScroll didn't seem to work anyway sadly), I discovered that I was applying simplelightbox to multiple items, and the handleScrollbar function was being called once for each item within a gallery of items.

Is there a way to implement galleries of images with only one thumbnail? (i.e. how do I add additional images to a gallery without adding a thumbnail on the original page?)

**Comment by andreknieriem** [comment]
Yo don't need thumbs. You only need elements with the selector.
You can see a working example here:
https://www.heuking.de/de/ueber-uns/standorte/kanzlei/berlin.html

HTML:
```
<div class="hidden-gallery-items" style="display:none">
<a href="img1.jpg">img</a>
<a href="img2.jpg">img</a>
<a href="img3.jpg">img</a>
</div>

<button class="open-gallery">Gallery</button>
```

JS:
```
var gallery = $('.hidden-gallery-items a').simpleLightbox();

$('.open-gallery').click(function(e){
    e.preventDefault();
    gallery.open($('.hidden-gallery-items a:first'));
});
```
