### ISSUE TITLE
Unable to preventDefault inside passive event listener due to target being treated as passive

### ISSUE THREAD

**Issue by YodasMyDad** [andreknieriem/simplelightbox#155]
Getting the follow error in Chrome on my touch screen laptop when I close the light box

> [Intervention] Unable to preventDefault inside passive event listener due to target being treated as passive. See https://www.chromestatus.com/features/5093566007214080

Doesn't appear when I use the mouse click to close, only when I use my touch screen to close.

**Comment by andreknieriem** [comment]
Thanks. Will be fixed soon.

**Comment by YodasMyDad** [comment]
NP. Thanks for a fantastic little library. Be amazing if this supported videos too.

**Comment by andreknieriem** [comment]
Fixed
