### ISSUE TITLE
Uniqualize images in gallery

### ISSUE THREAD

**Issue by alex-jitbit** [andreknieriem/simplelightbox#156]
If I have multiple links pointing to the same image, images will be duplicated in the carousel. Is there a way to loop through unique images only?

**Comment by andreknieriem** [comment]
Will take a look. I think it could be in v2.0.1

**Comment by Jonatan-r** [comment]
What's the status of this? I have the same request :)

**Comment by andreknieriem** [comment]
Nothing new, but will take a look soon.

**Comment by andreknieriem** [comment]
Got it to work. Will be in the next release.
