### ISSUE TITLE
No Documentation of Expected HTML Structure

### ISSUE THREAD

**Issue by machineghost** [andreknieriem/simplelightbox#158]
You've got really great documentation of the jQuery options, methods, etc. ... and then when it comes to the absolutely critical "your HTML needs to look a certain way for any of this to even work" part ... there's nothing in the documentation (there literally isn't any HTML code in the documentation at all).

All you get is your page yelling "Image not found, next image will be loaded" at you, with no clue as to what you've done wrong or how to fix it, in either that message or in the docs.  Anything you could change to combat this would likely be helpful for new people trying to use the library.

**Comment by andreknieriem** [comment]
That's a good point. Never thought that this could be a problem. Thanks for the hint. Will change this.
