### ISSUE TITLE
RTL support

### ISSUE THREAD

**Issue by ni-fara** [andreknieriem/simplelightbox#161]
Hi, I checked simplelightbox and it's great but unfortunately it doesn't support html pages with dir="rtl".
Navigation arrows are not displayed correctly
![Simple Lightbox-RTL-Direction Arrows Problem](https://user-images.githubusercontent.com/35923697/73139640-4f17a880-4085-11ea-84bf-8efbf7ef87a8.jpg)

I tried to correct it by putting below code to my site's stylesheet
```
.sl-navigation {
    direction: ltr;
}
```
The appearance get corrected but the slide direction doesn't, it should work like this:
-On LTR pages the right arrow points to next image (works fine now)
-On RLT pages the left arrow should point to next image (it doens't work as expected right now)

**Comment by andreknieriem** [comment]
Nice feature. I will take a look at this ;)

**Comment by ni-fara** [comment]
Great, @andreknieriem as an example owl carousel uses an option to manually set the direction, here is the demo [https://owlcarousel2.github.io/OwlCarousel2/demos/rtl.html](https://owlcarousel2.github.io/OwlCarousel2/demos/rtl.html)
It works by adding option rtl:true

**Comment by andreknieriem** [comment]
Added
