### ISSUE TITLE
New version not working

### ISSUE THREAD

**Issue by nativecreation** [andreknieriem/simplelightbox#162]
Hi. I've been using this plugin for a long time and have never had problems. After the last update, when the gallery grouping was added by rel attribute after hooking and script initialization, the first photo will appear, and no other action will be performed anymore. You cannot scroll to the next photo, and you cannot close the lightbox. I implement the pure JS version.

Anyone have a similar problem with it?

**Comment by andreknieriem** [comment]
Hey sorry to hear that. What browser are you using an did you change the name of the css file to simple-lightbox.css from simplelightbox.css?

**Comment by nativecreation** [comment]
Hi. I using Firefox and I using scss file from src catalogue and I imported that to global "style.scss" where I imported all scss files. All files are compiled / minified to one css file.

I used your lightbox in another script - "Swiper Slider".

Demo below:
http://nexstudio.stronazen.pl/demo/

**Comment by andreknieriem** [comment]
I just figured out, that i was missing the generated files by gulp for the latest release. My fault. Can you include the new updated version 2.1.0? I  see a JS Error in your demo ncaught TypeError: Cannot read property 'getAttribute' of null at Image.<anonymous> (simplelightbox.min.js:7). Will take a look what that means.

**Comment by nativecreation** [comment]
Ok, I include the newest version but doesn't working all the time.

**Comment by andreknieriem** [comment]
Should work now. There was a bug with the captions.
