### ISSUE TITLE
Can not import to project

### ISSUE THREAD

**Issue by wujido** [andreknieriem/simplelightbox#164]
Hi, sorry for probably stupid question, but i can't import library to my project. 
I have install it with `npm install simplelightbox`
I am trying to import it standard way: `import SimpleLightbox from 'simplelightbox';` or `let SimpleLightbox = require('simplelightbox');`
But I am not successfull. I think it's becouse there is no export in `dist/simple-lightbox.js`. If I try to add `export default SimpleLightbox` to this file, both methods works fine. But modify file in node_modules is definitely not great idea.
Is there something what I am missing?

Thanks for your time and any reply.

**Comment by andreknieriem** [comment]
Hey, never testet this. Will take a look soon.

**Comment by leoliu** [comment]
I am seeing this issue as well. Basically the only way to use it is through jQuery.

**Comment by andreknieriem** [comment]
Ok, not find a good solution for this until now. Will take a look in other js projects, how the handle it.

**Comment by leoliu** [comment]
I notice the project is using babel and wonder if change the first line of `src/simple-lightbox.js` will make it work?

Before
```
class SimpleLightbox {
```

After
```
export default class SimpleLightbox {
```

**Comment by andreknieriem** [comment]
This doesn't work for me.

**Comment by tomkiss** [comment]
I did this by adding `export { SimpleLightbox };' to the bottom of the simple-lightbox.js file.

Then `import { SimpleLightbox } from './vendor/simpleLightbox';` to import.

**Comment by andreknieriem** [comment]
Now in v2.2.0
