### ISSUE TITLE
Can't use HTML with navText

### ISSUE THREAD

**Issue by NicotineLL** [andreknieriem/simplelightbox#165]
Tried using an SVG icon (also tested with FontAwesome icons), but navigation buttons don't trigger if the icon/text is inside HTML regardless of what the docs say.

Managed to fix this by setting the parent HTML element inside the button with `position: relative` and `z-index: -1` (so it goes behind it), but this should probably be fixed inside the core?

**Comment by andreknieriem** [comment]
Ok I will take a look at this ;)
