### ISSUE TITLE
TypeError: Cannot use 'in' operator to search for 'close.simplelightbox' in undefined

### ISSUE THREAD

**Issue by leoliu** [andreknieriem/simplelightbox#167]
version: 2.1.2

`element.fullyNamespacedEvents` can be uninitialised in '.off' for example when '.on' is never used.

```
Uncaught (in promise) TypeError: Cannot use 'in' operator to search for 'close.simplelightbox' in undefined
    at SimpleLightbox.off (simple-lightbox.jquery.js:1602)
    at SimpleLightbox.destroy (simple-lightbox.jquery.js:1661)
```

**Comment by andreknieriem** [comment]
Hey, how can this happen? You close a never opened lightbox?

**Comment by leoliu** [comment]
I get the same error even if the lightbox has been opened.

In my case simpleLightbox is destroyed (if any) and initialised in a render function that gets called whenever the state changes. It was working flawlessly until the 2.0 update.

Reading the source of simple-lightbox.jquery.js it seems `element.fullyNamespacedEvents` is only initialised when `.on` is ever called.

**Comment by andreknieriem** [comment]
Alright. Thanks for your input. Will take a look and fix it ;)
