### ISSUE TITLE
double tap to zoom broken on mobile

### ISSUE THREAD

**Issue by leoliu** [andreknieriem/simplelightbox#168]
Visit https://simplelightbox.com/ on your phone and tap to open any of the images. Try double tap and the image will zoom in for a second and then immediately zoom out.

**Comment by Klenkes** [comment]
I can confirm. Android phone with Google Chrome the image snaps back immediately. With Opera(57.1) the image isn't scaled to the screen width and moved to right bottom. Strange...

(On my own website SimpleLightBox 1.17.2, everything's fine)

**Comment by andreknieriem** [comment]
Thanks. Fixed it ;)

**Comment by leoliu** [comment]
I just upgraded to 2.1.5 and had mixed results regarding this bug. double-tap-to-zoom works fine on an android device but barely working on latest mobile safari. On mobile safari double-tap never zooms but three or more taps in quick succession does.

**Comment by Klenkes** [comment]
I don't think that it's fixed, or... the bug is introduced back again. Look at the gifs below taken from the current website.

**This is Chrome on Android:** 
First a few douple taps, then pinching to zoom and dragging the image.
![bug-on-chrome](https://user-images.githubusercontent.com/5174937/80609533-7c834200-8a38-11ea-99b1-ebf6f3254563.gif)

**This is Opera on Android: (V 57.2....)**
The image is shifted to the right down(used to be another bug), and double tap shows same behaviour as Chrome.
![bug-on-opera](https://user-images.githubusercontent.com/5174937/80609826-dd127f00-8a38-11ea-8c01-b0aab53b6347.gif)

**Comment by andreknieriem** [comment]
Hm, strange, for it works. Will rake a look agsin. Thanks for finding out

**Comment by Klenkes** [comment]
If you need any more info or testing, don't hesitate to ask!

**Comment by andreknieriem** [comment]
So in v1.17.2 everything works? Even in Opera?

**Comment by Klenkes** [comment]
> So in v1.17.2 everything works? Even in Opera?
Yes, it's 1.17.2 See here: [https://www.qambium.com/de/unsere-objekte/skulpturen/drachenkopf/](url) It works on all devices I have access to. 

> And the other bug is #171
Works here as well.

**Comment by andreknieriem** [comment]
Ok the bug was on the github page. I've loaded simple-lightbox.js 2.0.0 on that page. Now it works. Please reload sometimes or open with incognito tab.

**Comment by andreknieriem** [comment]
Hey Klenkes, Ich sehe, du hast deutsche Namen in der Url. Das ist vielleicht einfacher. Also der Pan und das Bild flackert weg Bug ist bei dir auch behoben oder? BEstehend bleibt, dass der Opera sich verrechnet und das Doppelclick generell spinnt?

**Comment by Klenkes** [comment]
Das Android Opera Problem besteht weiterhin(in einem Private Tab), aaaber es kommt wohl daher, dass der Content rechts über den Viewport hinaus geht! Vermutlich wegen der Tabelle mit den Options, die sich nicht weit genug verschmälern kann.

Mhh... zum Testen bräuchte man eine vereinfachte Seite...

**Comment by Klenkes** [comment]
**ALL CLEAR! Everything works fine!**
I downloaded the latest release 2.1.5 from github and put it with the old demo case here:
[http://testcases.kopfleere.de/bilddarstellungen/simplelightbox/demo-215/](url)
Works perfectly on all my devices, even the iPad, with double tap, image pan, everything.

We all got confused on/with the Simplelightbox Github page. The options table is not very responsive and on small screens too wide for the viewport, so widths are calculated wrong(I guess)

**Comment by andreknieriem** [comment]
https://github.com/andreknieriem/simplelightbox/blob/master/demo/onlyImages.html. Thanks! I've added an old style only images demo page for this type of testing ;)
