### ISSUE TITLE
Spinner for multiple lightbox in a single page

### ISSUE THREAD

**Issue by Math3wC** [andreknieriem/simplelightbox#17]
Hi Andre, I'm following what you told me about multiple lightbox in https://github.com/andreknieriem/simplelightbox/issues/16
And I found out that the spinner (.sl-spinner) loading gif for image will not hide itself after closing the lightbox once it's been called out.

I also tested to have only 1 lightbox in the page and the spinner will hide after I close the lightbox.
This happens once the lightbox is more than 1 in a single page.

Could you please check?

**Comment by andreknieriem** [comment]
Hi, thanks for the bug issue. Will try to see what the problem is! Thanks

**Comment by Math3wC** [comment]
Argh, turned out to be false alarm. You have it fixed in last commit. Was using an older version of the scripts. Sorry for the troublesome.

**Comment by andreknieriem** [comment]
No problem!
