### ISSUE TITLE
Help with correct selector or new option

### ISSUE THREAD

**Issue by idflorin** [andreknieriem/simplelightbox#170]
Hello and great job.

I use in my js file

`var lightbox = new SimpleLightbox('.node--type-story .node-inner a', {
    /* options */ 
    alertError: false,
    captionsData: 'alt',
    fileExt: 'png|jpg|jpeg|gif',
    animationSpeed: 50,
    showCounter: 'true'
    });`

this works fine for

`<p>etc etc. <a href="/sites/default/files/media-insert/2020-Volkswagen-Touareg-luxury-suv-a03.jpg?itok=6_iukdCh"><img alt="Volkswagen Touareg" class="image-large photoswipe img-responsive" height="480" src="/sites/default/files/styles/large/public/media-insert/2020-Volkswagen-Touareg-luxury-suv-a03.jpg?itok=6_iukdCh" width="720"></a> . etc</p>`

but I don’t want it for

`<p>etc etc. <a href="https://www.spare-wheel.com/suv-cars/new-touareg-v8-tdi-most-powerful-volkswagen-market">Volkswagen Touareg luxury SUV</a> . etc</p>`
as you can see it's no image in the HTML above but it appears in gallery .

the question is how can you skip an a href without an img inside.

you can see the behaviour here: https://www.spare-wheel.com/suv-cars/dacia-duster-reaches-500000-unit-production-milestone
Here are 4 images but the gallery shows 5.

Any ideas?

Thank you very much.

**Comment by andreknieriem** [comment]
Hey, sorry but that's not a question for the lightbox itself.
But as I see in your site, every image is in a field--type-image div. So 

'.node--type-story .node-inner .field--type-image a' should do the trick. Or you need to give your a-tags some classes, or you can try to use a selector like document.querySelectorAll("a[href*='jpg'] (not tested)

**Comment by idflorin** [comment]
You are the best. It took me a while but I did it
this seems to work
`var $container = document.querySelector(".node--type-story");
if ($container !== null) {
var lightbox = $($container.querySelectorAll("a[href*='jpg']")).simpleLightbox({ 
    alertError: false,
    captionsData: 'alt',
    fileExt: 'png|jpg|jpeg|gif',
    animationSpeed: 10,
    showCounter: 'true'
    });
}`
