### ISSUE TITLE
React Support?

### ISSUE THREAD

**Issue by shaileshiyer** [andreknieriem/simplelightbox#172]
It would be nice if this was available in react. The simplicity and ease with which this was possible would be really helpful in react.

**Comment by andreknieriem** [comment]
What do I need to do for this? Not using react.

**Comment by shaileshiyer** [comment]
hey andre, I had just noticed the email in my inbox. 
I would be willing to help out with trying to create the library as a bunch of components that can be utilised in either react or vue. 
I was thinking about having a controlled and an uncontrolled component for the lightbox.

**Comment by andreknieriem** [comment]
Hey. I close this as I don't know what to do. There is a vue simple lightbox plugin. I don't know if it is updated.
