### ISSUE TITLE
Issue In Mobile When Touch Swipe Up or Down

### ISSUE THREAD

**Issue by abhisekrathi** [andreknieriem/simplelightbox#174]
On Mobile Devices, touch can be used to swipe left and right to move to next & previous photos. But when touch is used to swipe up or down, even though it closes the opened image & overlay, there is an error on:
https://cdnjs.cloudflare.com/ajax/libs/simplelightbox/2.1.5/simple-lightbox.js Line 624

key: "setZoomData",
    value: function setZoomData(initialScale, targetOffsetX, targetOffsetY) {
      this.currentImage.dataset.scale = initialScale;
      this.currentImage.dataset.translateX = targetOffsetX;
      this.currentImage.dataset.translateY = targetOffsetY;
    }

Issue seems to be that as both pointerup & touchend are getting fired at Line Number 883, when pointerup gets fired, the code is executed and _this6.close() is called on Line 936 due to:
if (_this6.options.swipeClose && Math.abs(_this6.controlCoordinates.swipeYDiff) > 50 && Math.abs(_this6.controlCoordinates.swipeDiff) < _this6.options.swipeTolerance)
          
But immediately after that, when touchend gets fired, _this6.currentImage is Null causing the error "Cannot read property 'dataset' of null". Ideally, it should have another condition in Line 884 for _this6.currentImage == Null so that it does not enter the code area.

Not sure if that will break anything else in the code.

And keep up the good work.

**Comment by abhisekrathi** [comment]
Issue seems to be that both pointerup & touchend are getting fired at Line Number 883. When pointerup gets fired, the code is executed and _this6.close() is called. But immediately after that, touchend gets fired and this time, _this6.currentImage is Null causing the error "Cannot read property 'dataset' of null"
No idea how to resolve it.

**Comment by andreknieriem** [comment]
Fixed in v2.2.1

**Comment by abhisekrathi** [comment]
That was fast. Really appreciate it Andre!!

**Comment by abhisekrathi** [comment]
Hi Andre,
I think there is a similar issue at v2.2.1 Line 644:
this.controlCoordinates.imgHeight =
this.getDimensions(this.currentImage).height;
this.controlCoordinates.imgWidth =
this.getDimensions(this.currentImage).width;

I am getting error on it very frequently on TrackJS as my users are using
the site. However, as I am not able to generate the error at my end, I am
unable to get the exact flow which causes it.

Errors:

Argument 1 ('element') to Window.getComputedStyle must be an instance of
Element
Failed to execute 'getComputedStyle' on 'Window': parameter 1 is not of
type 'Element'.
<https://my.trackjs.com/errors/filtered?hash=90b514a5d975fca>

depending on if it is Android or iOS
