### ISSUE TITLE
Issue when gallery opened using double click/double touch

### ISSUE THREAD

**Issue by abhisekrathi** [andreknieriem/simplelightbox#179]
Hi Andre,
Sample: https://www.maheshwari.org/user/profile2.aspx?id=8077
If the user opens the photo gallery by single touch/click, eveything is smooth. However, if the user opens the gallery using double click/double touch, there is some issue in initialization. The left and right arrows don't get displayed. Also, when the user taps on the image in such a senario, it gives errors:
Argument 1 ('element') to Window.getComputedStyle must be an instance of Element
Failed to execute 'getComputedStyle' on 'Window': parameter 1 is not of type 'Element'.
depending on if it is Android or iOS

The error which is coming is at v2.2.1 Line 644:
this.controlCoordinates.imgHeight =
this.getDimensions(this.currentImage).height;

**Comment by andreknieriem** [comment]
This does not happen here. Can you show me a page where this happened?

**Comment by andreknieriem** [comment]
Closed due to no info

**Comment by abhisekrathi** [comment]
Hi Andre,
I have been using your lightbox for past 4 years now and this issue still occurs intermittently. Another error which comes intermittently is:
Uncaught TypeError: Cannot read properties of undefined (reading '0').
I have recently updated to 2.14.1 version but it still remained unresolved. I been using the minified version of the lightbox but have recently switched to normal version so as to share with you more data on the line number etc for both these errors.
