### ISSUE TITLE
Prev / Next buttons appear even if there just one image

### ISSUE THREAD

**Issue by Yannick-Valentin** [andreknieriem/simplelightbox#18]
If I put the lightbox on a single link, the prev / next buttons are showing.

Example : http://codepen.io/yvalentin/pen/LGNzmB

**Comment by andreknieriem** [comment]
Thanks, will fix it in the next version

**Comment by nicekiwi** [comment]
This is not a bug, by default the photos loop. So with a single image; it will loop that one image. You could be technical and say no one wants arrows on a single image loop, but #yolo. 

To fix this just pass the option { loop:false } when you init the lightbox.

**Comment by andreknieriem** [comment]
I think it is a bug, because if you have multiple pages and on some of them only 1 image you want the loop feature, but not for 1 image. So I will fix it in the next version.

**Comment by nicekiwi** [comment]
:+1:

**Comment by andreknieriem** [comment]
fixed in version 1.7.0!
