### ISSUE TITLE
Unable to use with parcel bundler

### ISSUE THREAD

**Issue by sunnysolanki89** [andreknieriem/simplelightbox#183]
Using 
import SimpleLightbox from "simplelightbox";
new SimpleLightbox('.grid .grid-item a', {});

Getting error
Uncaught TypeError: _simplelightbox.default is not a constructor

**Comment by andreknieriem** [comment]
Can you try to import from simplelightbox.modules.js?

**Comment by LouVerdun** [comment]
This works in a dirty way by reaching for the file itself in the `node_modules`.
```
import SimpleLightbox from "../../../node_modules/simplelightbox/dist/simple-lightbox.modules";
```

**Comment by andreknieriem** [comment]
Should work now a way better.
