### ISSUE TITLE
Disabling animations slide option seems not to make any difference 

### ISSUE THREAD

**Issue by csalmeida** [andreknieriem/simplelightbox#186]
Thank you for sharing this lightbox, it works really well and it does so much. 🙏

Can someone expand on how the `animationSlide` options effects are on the lightbox? Are they meant to disable animations altogether?

If this is the case, this options seems to make no difference when I introduce it in an `SimpleLightbox` instance as an option:

```javascript
    var lightbox = new SimpleLightbox('.js-gallery a', {
      animationSlide: false,
    });
```

Any thoughts on why this might not be taking effect at all?

**Comment by andreknieriem** [comment]
Hi, no it means, that the image is not sliding when using the keys on the keyboard, or the next and previous button or touch and swipe.

**Comment by andreknieriem** [comment]
use it with fadeSpeed: 0 to make this go faster ;) See latest release

**Comment by csalmeida** [comment]
Thank you for getting back to me @andreknieriem, will have a look when I can!
