### ISSUE TITLE
Object doesn't support this action [IE11]

### ISSUE THREAD

**Issue by jfgirard** [andreknieriem/simplelightbox#192]
Hi,

I tried to upgrade from 1.16 to 2.2.1 (latest) but I get a bug on IE 11 (sadly I need to support it).

`Object doesn't support this action`  at line
  `element.dispatchEvent(new Event('show.' + this.eventNamespace))` 
of `openImage` function;

Works fine on other browsers.

**Comment by andreknieriem** [comment]
Yes the IE makes some errors. I try to see what I can do for this.
