### ISSUE TITLE
Issue with multiple light boxes on one page

### ISSUE THREAD

**Issue by jacklawry** [andreknieriem/simplelightbox#193]
I have a page with multiple light boxes and it works well except if you open a lightbox set with multiple images it all works fine but if you then open only a single image lightbox (so the left and right arrows are not shown as a expected) then open anything else the arrows seem to be permanently removed. 

Is there a fix for this?

**Comment by andreknieriem** [comment]
Hey this doesn't happen here. Do you have an example?

**Comment by jacklawry** [comment]
The site is not live yet so I am just waiting for permission from the client to send you a development link but I will email you if thats ok & Include a reference to this issue?

**Comment by jacklawry** [comment]
> The site is not live yet so I am just waiting for permission from the client to send you a development link but I will email you if thats ok & Include a reference to this issue?

I have sent you an email (via your https://www.andrerinas.de contact form)

**Comment by jacklawry** [comment]
> > The site is not live yet so I am just waiting for permission from the client to send you a development link but I will email you if thats ok & Include a reference to this issue?
> 
> I have sent you an email (via your https://www.andrerinas.de contact form)

Hi @andreknieriem 

Have you received this email? 
Is there something I need to do differently or is this a bug?

Thanks,
Jack

**Comment by andreknieriem** [comment]
Hey, sorry your mail doesn't arrive. Can you send it to info@andrerinas.de directly?

**Comment by jacklawry** [comment]
Updating to the latest version seems to resolve this issue.

**Comment by jacklawry** [comment]
Sorry this issue still does remain
