### ISSUE TITLE
Fixed elements are "moving" when lightbox is triggered

### ISSUE THREAD

**Issue by sooroos** [andreknieriem/simplelightbox#195]
Because the "body" is set to have overflow: hidden when the lightbox is opened, fixed elements, like menu for example are moving. Can you fix this? take a look at the bootstrap modal: the body becomes a padding-right = scrollbar width when the modal is opened and there are some css classes too with the same padding-right, like "fixed-top". You should define a class for something like that too

**Comment by andreknieriem** [comment]
This is implement since years. https://simplelightbox.com/ you can see this here. Which browser are you using?

**Comment by sooroos** [comment]
please read what i wrote one more time. What i said, it is that a class is needed for extra padding right (which should equal scrollbar width)
For example, if you have an element fixed top (left:0, top:0, right:0) it moves 17px right (in chrome desktop) when lightbox is triggered
https://basic.unit08.de/ueber-uns/ check the gallery under "Team" and watch the menu moving

**Comment by andreknieriem** [comment]
Ok, now I understand what you mean. Good point, I will add a class, which can be changed to enable right paddings for fixed elements. Sorry for closing this ;)

**Comment by sooroos** [comment]
thank you very much, im also sorry i didnt explain it very well for the first time

**Comment by andreknieriem** [comment]
Added sl-fixed as a class in v2.4.0
