### ISSUE TITLE
Stuck in loading on Safari (iOS + macOS)

### ISSUE THREAD

**Issue by y1337x** [andreknieriem/simplelightbox#197]
When I'm clicking on an image, simple lightbox is stuck in the loading procedure. The main div still has these classes: slbElement slbLoading slbLoading. In Chrome and Firefox, simple lightbox works just fine and the class list of the main div is reduced to slbElement as it should be. I don't know what is happening, there are no errors in the console.

**Comment by andreknieriem** [comment]
Hi there. Are you sure you are in the right repo? I don't use classes like slbElement and slbLoading.

**Comment by y1337x** [comment]
Hi, I was looking into the problem again and you're right! Currently, I'm using https://github.com/dbrekalo/simpleLightbox where the error occurs. So, I'm sorry for confusing your libs and I will try your code now :)
