### ISSUE TITLE
This lightbox works with videos?

### ISSUE THREAD

**Issue by jadersilvabr** [andreknieriem/simplelightbox#198]
Hello everyone,

This lightbox works with videos? If yes, could you share an example?

I tried this, but did not works:

```
<div class="videoGameGallery">
   <a href="http...">
      <img src="x.jpg"
   </a>
</div>

var $galleryv = new SimpleLightbox('.videoGameGallery a', {});
```

Regards.

**Comment by andreknieriem** [comment]
Hi, sorry this is not planned. It only works with images. Maybe some day in the future.
