### ISSUE TITLE
Events doesn't fire in jquery

### ISSUE THREAD

**Issue by Stozen-spb** [andreknieriem/simplelightbox#199]
In a demo file index.html I changed plugin version to jquery:
<script src="../dist/simple-lightbox.jquery.min.js"></script>
And wrote this 
```
          //var $gallery = new SimpleLightbox('.small-demo a', {});
		$('.small-demo a').simpleLightbox();
		$('.small-demo a').on('show.simplelightbox', function () {
			// do something…
			alert(3)
		});
		$('.small-demo a').on('closed.simplelightbox', function () {
			// do something…
			alert(3)
		});
```
Events doesn't work.

**Comment by Stozen-spb** [comment]
In old versions (like 2017) it works fine.

**Comment by andreknieriem** [comment]
You're right. I take a look on how to fix this ;)

**Comment by Stozen-spb** [comment]
var lightbox = $('.small-demo a').simpleLightbox();
		lightbox.on('show.simplelightbox', function () {
			// do something…
			alert(3)
		});
This style works fine.

**Comment by andreknieriem** [comment]
You're right. I need to change the documentation.

**Comment by andreknieriem** [comment]
Fixed the documentation. Thanks for the hint
