### ISSUE TITLE
How to make it work with Owl Carousel structure ?

### ISSUE THREAD

**Issue by Webmania-tech** [andreknieriem/simplelightbox#203]
Hello,
Thank you for this excellent lightbox, I'd really like to use it on my website. But I have to combine it with Owl Carousel.
Owl Carousel has a different HTML structure than the one displayed on the documentation.
I know a similar issue has been posted in 2018, closed now, called "SimpleLightBox with OwlCarousel #117" but it didn't worked for me.
Here is my HTML structure :
```
<div class="owl-carousel owl-theme lightbox">
  <div class="item">
    <a href="myimg.jpg">
      <img src="myimg.jpg" alt="My image" />
    </a>
  </div>
  <div class="item">
    <a href="myimg.jpg">
      <img src="myimg.jpg" alt="My image" />
    </a>
  </div>
  <div class="item">
    <a href="myimg.jpg">
      <img src="myimg.jpg" alt="My image" />
    </a>
  </div>
</div>
```

And then the script I tried :

`var lightbox = $('.owl-item a').not('.cloned').simpleLightbox();`

I tried many other options but nothing worked. Only the first image displays the overlay and when I use the nav it says "Image not found, next image will be loaded". I hoped you could help.

Best regard,
Anna

**Comment by andreknieriem** [comment]
In your html structure is no owl-item a. Maybe you need to start the lightbox after the owl carousel is initialized. 
And you say no a tag with class cloned. Thats just wrong.

var lightbox = $('.owl-item').not('.cloned').find('a').simpleLightbox();

**Comment by Webmania-tech** [comment]
Ok, thank you for your answer.

**Comment by andreknieriem** [comment]
Closed for now
