### ISSUE TITLE
Allow captionSelector to be a callback function which returns an element

### ISSUE THREAD

**Issue by ocean90** [andreknieriem/simplelightbox#205]
`captionSelector`  is currently limited to a selector which is either the lightbox element itself or a child element of the lightbox element due to the use of `querySelector()`.  Therefore it's not possible to use a sibling element. What I would like to propose is an API as follows:

```js
new SimpleLightbox( image, {
	captionType: 'text',
	captionSelector: ( element ) => element.nextElementSibling,
} );
```

The `element` argument passed to my callback would be `this.relatedElements[this.currentImageIndex]`.

I'm happy to provide a PR if this idea gets accepted.

**Comment by andreknieriem** [comment]
Sounds like a good idea. A pull request would be great.
