### ISSUE TITLE
Initializing with custom HTML structure.

### ISSUE THREAD

**Issue by Internalizable** [andreknieriem/simplelightbox#207]
I have the following HTML structure:

<div class="row padding">
        
        <div class="col-md-3">
            <div class="card">
                    <a href="img/gallery/art.jpg"><img class="card-img-top" src="img/gallery/art.jpg"></a>
                
                <div class="card-body">
                    <p class="card-text">
                        Hello world!
                    </p>
                </div>
            </div>
        </div>
        <div class="col-md-3">
            <div class="card">
                <a href="img/gallery/art.jpg"><img class="card-img-top" src="img/gallery/art.jpg"></a>
                <div class="card-body">
                    <p class="card-text">
                        Hello world!
                    </p>
                </div>
            </div>
        </div>
        <div class="col-md-3">
            <div class="card">
                <a href="img/gallery/art.jpg"><img class="card-img-top" src="img/gallery/art.jpg"></a>
                <div class="card-body">
                    <p class="card-text">
                        Hello world!
                    </p>
                </div>
            </div>
        </div>
        <div class="col-md-3">
            <div class="card">
                <a href="img/gallery/art.jpg"><img class="card-img-top" src="img/gallery/art.jpg"></a>
                <div class="card-body">
                    <p class="card-text">
                        Hello world!
                    </p>
                </div>
            </div>
        </div>
    </div>
    <div class="row padding">
        <div class="col-md-3">
            <div class="card">
                <a href="img/gallery/art.jpg" data-lightbox="arts"><img class="card-img-top" src="img/gallery/art.jpg"></a>
                <div class="card-body">
                    <p class="card-text">
                        Hello world!
                    </p>
                </div>
            </div>
        </div>
        <div class="col-md-3">
            <div class="card">
                <a href="img/gallery/art.jpg" data-lightbox="arts"><img class="card-img-top" src="img/gallery/art.jpg"></a>
                <div class="card-body">
                    <p class="card-text">
                        Hello world!
                    </p>
                </div>
            </div>
        </div>
        <div class="col-md-3">
            <div class="card">
                <a href="img/gallery/art.jpg" data-lightbox="arts"><img class="card-img-top" src="img/gallery/art.jpg"></a>
                <div class="card-body">
                    <p class="card-text">
                        Hello world!
                    </p>
                </div>
            </div>
        </div>
        <div class="col-md-3">
            <div class="card">
                <a href="img/gallery/art.jpg" data-lightbox="arts"><img class="card-img-top" src="img/gallery/art.jpg"></a>
                <div class="card-body">
                    <p class="card-text">
                        Hello world!
                    </p>
                </div>
            </div>
        </div>
    </div>

I've tried to initialize SimpleLightbox but it's not working; it only works for the first element of (.card a) and doesn't do for the rest. Any help?

**Comment by andreknieriem** [comment]
Hey. Your markup looks valid. Can you give me a link where I can see it?

**Comment by andreknieriem** [comment]
Closed because of no answer
