### ISSUE TITLE
window explorer error.

### ISSUE THREAD

**Issue by moko2man** [andreknieriem/simplelightbox#208]
SimpleLightbox works good at chrome. But it doesn't work at explorer. 
It says, 

Object does not support'assign' property or method.

error massage: 

SCRIPT438: 개체가 'assign' 속성이나 메서드를 지원하지 않습니다.
simple-lightbox.min.js (1,1925)

**Comment by andreknieriem** [comment]
Hey, if you really need Internet Explorer Support, you have to use the simple-lightbox.legacy.js or simple-lightbox.legacy.min.js
