### ISSUE TITLE
Doesn't work properly when images url are the same

### ISSUE THREAD

**Issue by karol-pietrzak** [andreknieriem/simplelightbox#209]
Rather minor issue but almost made me think that this script doesn't work at all.

While developing i wanted to make gallery made of one image multiplied many times.

In that case only first image will have lightbox

If gallery is made of different urls then its working as it supposed to

```
<div class="gallery">
    <a href="image.jpg">
        <img src="image.jpg" alt="" title="">
    </a>
    <a href="image.jpg">
        <img src="image.jpg" alt="" title="">
    </a>
    <a href="image.jpg">
        <img src="image.jpg" alt="" title="">
    </a>
    <a href="image.jpg">
        <img src="image.jpg" alt="" title="">
    </a>
    <a href="image.jpg">
        <img src="image.jpg" alt="" title="">
    </a>
</div>
```

**Comment by andreknieriem** [comment]
Hey. Not an issue, it is a feature. The option here is **uniqueImages**

See: 
uniqueImages | true | bool | whether to uniqualize images or not which is by default true.

**Comment by karol-pietrzak** [comment]
@andreknieriem ah cool! Please make it distinct in docs, it is not that trivial  :D
