### ISSUE TITLE
global is not defined

### ISSUE THREAD

**Issue by dmh** [andreknieriem/simplelightbox#211]
Hey, 
I noticed that you added this line of code `global.SimpleLightbox = SimpleLightbox;`, and because of that, I got this error `global is not defined` when updated the plugin. In general, it is not a problem, I can remove it by myself, I am just curious for what reason, might be I shouldn't remove it. I will be really appreciated the explanation.

I am using `simple-lightbox.esm.js` and `Rollup` to import it.

Thank you.

**Comment by andreknieriem** [comment]
Ok. For browserify and webpack define the global var. Please just use something like: 
`const global = window;`
best regards
