### ISSUE TITLE
Body content scrolls to the bottom when lightbox is opened

### ISSUE THREAD

**Issue by aadam86** [andreknieriem/simplelightbox#212]
I've updated the simpleLightbox to version 2.7.0 and now when you open the lightbox gallery, the page content behind it, scrolls to the bottom of the page. When you close the lightbox, it's back where the gallery is in the page. I've checked both on Chrome and Firefox.

On version 2.5.0 when you open the lightbox, there's no bottom page scrolling.

**Comment by aadam86** [comment]
I found my issue. I forgot to update the css file:). Please close this.

**Comment by andreknieriem** [comment]
Alright ;) Thanks for using the plugin :)
