### ISSUE TITLE
Links in overlay not working in Safari 9.0.1

### ISSUE THREAD

**Issue by spleeen1** [andreknieriem/simplelightbox#214]
Hello, 
I am not sure, if this is the right place to post this, but I tried to implement the lightbox in my page and it works in every browser I have been testing with, only in Safari 9 (OSX) the links in the overlay don't work: arrows, close on overlay-click and close-x included. I don't even know if Safari 9 is supported at all, but just wanted to let you know.

**Comment by andreknieriem** [comment]
Hi thanks for your issue, but I am not able to test this and I wont support Safari 9 ;) Thanky anyway
