### ISSUE TITLE
Issue when previous or next image is loaded (iOS)

### ISSUE THREAD

**Issue by spleeen1** [andreknieriem/simplelightbox#215]
I tested my implementation of the lightbox today two iOS devices. Newest iPad with Safari and Chrome and also iPhone running Safari. 

Behavior: Clicking several times on eather Prev or Next link in overlay. At some random point LB closes and can't be opened again. Only on page refresh or destroy event it starts working again.

The issue is reproducable only with iOS, on windows no problems at all and also not in Mac osX with chrome/forefox. Safari above 9 seems to be working fine as well.

Idea: Can it be that the LB closes when the image is not loaded yet? 

*EDIT* 
Just to be sure, I also tried it directly on https://simplelightbox.com and the problem also shows here. SOmetime it works great, and then randomly, LB crashes.

**Comment by andreknieriem** [comment]
Hm that is very difficult to reproduce. I don't own an iOS Device, but I will try to take a look at this.

**Comment by spleeen1** [comment]
Thank you!

**Comment by andreknieriem** [comment]
I think this is fixed
