### ISSUE TITLE
Browser scroll to top when overlay shows up

### ISSUE THREAD

**Issue by RolandTi** [andreknieriem/simplelightbox#216]
Maybe it's the way I write css, because the glitch doesn't happen on SimpleLightbox's homepage, but when I click on a picture, the browser scroll to top on the background. Tested on Opera, Firefox & Safari.
https://eviltwin.vibvib.fr/croquis-story-boards/

Thanks for your help :-)

**Comment by andreknieriem** [comment]
Hey there, I will take a look at this ;)

**Comment by RolandTi** [comment]
Thank you !

**Comment by andreknieriem** [comment]
I don't get the error. Sorry. It seems to have to do something with your markup/scripts und styles, but I don't find out what the problem is. Sorry.

**Comment by RolandTi** [comment]
Ok, thanks ! I'll check the css.

**Comment by RolandTi** [comment]
Ok, I found ! 
The bug came from using
```
 html, body {
	height: 100%;
}
```
and the 
`body.hidden-scroll {
	overflow: hidden
}`
from simple-lightbox.

So I commented the simple-lightbox line and it's ok now.

**Comment by AlexByte** [comment]
@RolandTi https://github.com/andreknieriem/simplelightbox/issues/11
