### ISSUE TITLE
endless loading

### ISSUE THREAD

**Issue by andrconstruction** [andreknieriem/simplelightbox#22]
Thanks for your application. But has a little problem. If an image doesn't exist, a load working endless and I have no method how to close viewer until to full refresh a page

**Comment by andreknieriem** [comment]
Hi, thanks for your feedback, I will look at this. Doesn't ESC key work?

**Comment by andrconstruction** [comment]
Yes, an Esc key dont't work too, all looks like freezing

**Comment by andreknieriem** [comment]
Yes, I see whats going on. What do you think should happen? An alert, skip the image, or just close the lightbox with a message?

**Comment by andrconstruction** [comment]
I think that weil be better skip the image with an alert or make it optional

**Comment by andreknieriem** [comment]
Done in 1.7.1
