### ISSUE TITLE
add a Border around the images 

### ISSUE THREAD

**Issue by elieadib** [andreknieriem/simplelightbox#220]
Hi Andre

Thank you very much for the great JS, I'm using it for my personnal website

1 question, How can I add a Border around the images when scrolling with the arrows ?

Appreciate your support

Note I made a donation

**Comment by andreknieriem** [comment]
Hi I don't get what you want to do? Add a border only when the image swipes?

**Comment by elieadib** [comment]
Hi Andre,

I need to add a white border around the pictures when i'm viewing them in lightbox with the arrows
see attchement
<img width="798" alt="Screenshot 2021-01-22 at 09 18 26" src="https://user-images.githubusercontent.com/77684816/105465144-db59ad00-5c92-11eb-88d0-ff083d726baa.png">

Appreciate your support

**Comment by andreknieriem** [comment]
Sorry. I don't give any integration tips.
