### ISSUE TITLE
Overlay color & opacity

### ISSUE THREAD

**Issue by robinibbo** [andreknieriem/simplelightbox#225]
Hi, I really appreciate your simplelightbox, a lot better than many out there and I've tried a lot.

I am relatively new to coding and just need some assistance to change the color/opacity of the overlay on the image preview, I would ideally like to turn it dark, rather than light.  Thank you

**Comment by andreknieriem** [comment]
Hi. In the file: https://github.com/andreknieriem/simplelightbox/blob/master/src/simple-lightbox.scss is the background color as a variable. $sl-overlay-background. You can change this to black (#000). After that you need to call gulp build to rebuild the source files. Or you just edit the .css file directly, but this will be overriden by an update.

**Comment by robinibbo** [comment]
Thank you very muchRobin Sent from Mail for Windows 10 From: Andre RinasSent: 08 February 2021 07:48To: andreknieriem/simplelightboxCc: robinibbo; AuthorSubject: Re: [andreknieriem/simplelightbox] Overlay color & opacity (#225) Hi. In the file: https://github.com/andreknieriem/simplelightbox/blob/master/src/simple-lightbox.scss is the background color as a variable. $sl-overlay-background. You can change this to black (#000). After that you need to call gulp build to rebuild the source files. Or you just edit the .css file directly, but this will be overriden by an update.—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
