### ISSUE TITLE
How to let users download the images ?

### ISSUE THREAD

**Issue by dev-eduka** [andreknieriem/simplelightbox#226]
hello,

Great work on this library, very reliable and easy to use!
I was wondering if it's possible somehow to have a way to let users download the images. 
Or, view the full image source (.jpg original file) in a new tab, or something like that.

I went through all the options and I couldn't figure out how to do it.
Any ideas?

**Comment by philippemellenger** [comment]
Same issue here, would love to be able to add a download button.

**Comment by andreknieriem** [comment]
Added in new version
