### ISSUE TITLE
Bug when trying to drag images around or swipe on Firefox since 2.0.0

### ISSUE THREAD

**Issue by DrMint** [andreknieriem/simplelightbox#228]
Hello!

I've been using simplelightbox 1.17.2 for a while on my website. Today I decided on updating it to the latest version, 2.7.0.
Unfortunately, I found a problem: after zooming on the image with a double click, it's not possible to drag the image around with left click mouse. It's possible to do it with the middle click (if overflow is hidden). Doing it with right click kind of works but opens the menu. This problem also affect the ability for Firefox users to change the current image using swipe gesture with the mouse.

The problem can be replicated on your website [https://simplelightbox.com](https://simplelightbox.com), so I'm confident it's not a mistake on my side.

- I couldn't replicate the problem on Chrome, only while using Firefox (87.0, I didn't tried other versions of Firefox).
- On Firefox Android, dragging using touch control works as intended.
- I tried a few versions such as 2.7.0, 2.6.0, 2.1.4, and 2.0.0, they all present the same problem. 1.17.3 was working fine so I'm guessing it's something that was introduced with your complete rewrite.

**Comment by andreknieriem** [comment]
Hey, that's true. I will take a look!

**Comment by DrMint** [comment]
I've being able to fix most problems adding
```
pointer-events: none;
user-drag: none;
user-select: none;
```
to .sl-wrapper .sl-image img in the simple-lightbox.css.
However it introduces another problem with Chrome where the image becomes draggable (display a ghost image) when zoomed-in and the cursor leave sl-image's area while panning the image with the mouse.

**Comment by DrMint** [comment]
Bingo! It probably needs more testing just to be sure but I've added a event.preventDefault() line 737 in simple-lightbox.js and as far as I can tell, it's working perfectly

**Comment by andreknieriem** [comment]
Wow thanks, it is line 685 in the src file. I've spent 1 hour to find a solution, but it was that simple :D Thanks!

**Comment by DrMint** [comment]
No problem, glad we got it sorted!
