### ISSUE TITLE
WRONG package.json: dependencies instead devDependencies

### ISSUE THREAD

**Issue by coderars** [andreknieriem/simplelightbox#236]
`package.json` has development only packages listed as `dependencies` instead of `devDependencies`:

```json
  "dependencies": {
    "browserify": "^17.0.0",
    "core-js": "^3.6.5"
  } 
```

Now after running `npm i -P simplelightbox` it installs tons of packages needed only for development:

````log
added 175 packages, and audited 183 packages in 10s
````

**Comment by andreknieriem** [comment]
Good point. Fixed and will be in the next release!
