### ISSUE TITLE
Not working when using GET parameters. // Workaround 'fileExt' : false

### ISSUE THREAD

**Issue by steiha** [andreknieriem/simplelightbox#237]
The gallery does not work when using GET parameters. Eg. if generating images dynamically.

I am not quite sure if I should consider this as a bug. 
As a workaround I could disable the file extension check via the options.

'fileExt' : false

But maybe this should be stated in the documentation.

As an example see a real use:

https://www.chordsheet.com/song/png/39?transpose=2

The images are generated dynamically using GET parameters.

https://www.chordsheet.com/song/39-1.png?transpose=2
https://www.chordsheet.com/song/39-2.png?transpose=2

I really love your gallery script, great job, thank you!

**Comment by andreknieriem** [comment]
Hi, that is exactly for what the option fileExt: false is ;) Thanks for your issue and for your feedback!

**Comment by steiha** [comment]
Ok, thank you.
