### ISSUE TITLE
drag image on firefox

### ISSUE THREAD

**Issue by zurriaga** [andreknieriem/simplelightbox#239]
can´t drag a image on firefox

**Comment by zurriaga** [comment]
if i put this it works

$(document).on("dragstart", function(e) {
     if (e.target.nodeName.toUpperCase() == "IMG") {
         return false;
     }
});

**Comment by andreknieriem** [comment]
Can you tell me, which firefox version you have and on which device? For me dragging works without any problem. Do you use version 2.7.1 or later? It is fixed in 2.7.1.

**Comment by andreknieriem** [comment]
Closed
