### ISSUE TITLE
captionPosition

### ISSUE THREAD

**Issue by andrconstruction** [andreknieriem/simplelightbox#24]
Is it possible make combined value for captionPosition like 'top outside' or 'bottom outside'. If I set top, in this case the caption covers a part of image, but should be above the image like the value  'outside'

**Comment by andreknieriem** [comment]
Not possible yet. I will take a look if outside-top is possible without calculate the position via javascript and build it in.

**Comment by andreknieriem** [comment]
It's not possible with pure css and JS calculation is ugly. So outside to the top is not possible. - Won't fix
