### ISSUE TITLE
[FR] Passive touch event listeners (to pass Google Lighthouse performance tests)

### ISSUE THREAD

**Issue by coderars** [andreknieriem/simplelightbox#240]
The `touchstart` and `touchmove` events used by this plugin make Google Lighthouse (performance tests) complaining about "[Use passive listeners to improve scrolling performance](https://web.dev/uses-passive-event-listeners/)".

[Passive event listeners](https://github.com/WICG/EventListenerOptions/blob/gh-pages/explainer.md) cannot use `preventDefault()` and looking at the source code, it is used a lot in touch event handlers, so unfortunately fixing it seems complicated (to me).

My experiment using the suggested [feature detection](https://github.com/WICG/EventListenerOptions/blob/gh-pages/explainer.md#feature-detection) and hacking the `addEventListener` [method ](https://github.com/andreknieriem/simplelightbox/blob/731bf85475ae95c5e564f24c9d6365bc7c17483e/src/simple-lightbox.js#L1161) of this plugin to set the options variable to `{passive: true}` for the `touchstart` and `touchmove` events made the plugin OK for Google Lighthouse, also testing this hacked version showed no errors, simplelightbox seemed to work fine during my tests, however, because of this `preventDefault()` limitation, this hack is not safe I think...

@andreknieriem could you please consider adding this feature? Personally, this is the only/last thing why my site gets 99/100. Thank you!

**Comment by coderars** [comment]
Actually, there's only 2 affected touch listeners using `preventDefault`: [Line 680](https://github.com/andreknieriem/simplelightbox/blob/731bf85475ae95c5e564f24c9d6365bc7c17483e/src/simple-lightbox.js#L680) and [Line 773](https://github.com/andreknieriem/simplelightbox/blob/731bf85475ae95c5e564f24c9d6365bc7c17483e/src/simple-lightbox.js#L773)

**Comment by andreknieriem** [comment]
Hey, thanks for your suggestions. Can you provide your code? I need to look at this, because the preventDefault is for stopping browsers to follow anchor tags.

**Comment by coderars** [comment]
Sure! These were my modifications:

### Adding a new method for testing support:
````js
    checkPassiveEventsSupport() {
        // https://github.com/WICG/EventListenerOptions/blob/gh-pages/explainer.md#feature-detection
        // Test via a getter in the options object to see if the passive property is accessed
        let supportsPassive = false;

        try {
            let opts = Object.defineProperty({}, 'passive', {
                get: function() {
                    supportsPassive = true;
                }
            });
            window.addEventListener("testPassive", null, opts);
            window.removeEventListener("testPassive", null, opts);
        } catch (e) {}

        // console.log('simple-lightbox checkPassiveEventsSupport:', supportsPassive);

        return supportsPassive;
    }
````
### Calling it in the constructor and store its result:
````js
this.isPassiveEventsSupported = this.checkPassiveEventsSupport();
````
### Using the fix in the existing addEventListener method:
````js
    addEventListener(elements, events, callback, opts) {
        elements = this.wrap(elements);
        events = this.wrap(events);

        for (let element of elements) {
            if (!element.namespaces) {
                element.namespaces = {};
            } // save the namespaces addEventListener the DOM element itself

            for (let event of events) {
                let options = opts || false;

                // fix: use passive events (Google Lighthouse/PageSpeed)
                let needsPassiveFix = ['touchstart', 'touchmove'].indexOf(event.split('.')[0]) >= 0;
                if (needsPassiveFix && this.isPassiveEventsSupported) {
                    if (typeof options === 'object') {
                        options.passive = true;
                    } else {
                        options = {passive: true};
                    }
                    // console.log('simple-lightbox', event, options);
                }

                element.namespaces[event] = callback;
                element.addEventListener(event.split('.')[0], callback, options);

            }
        }
    }
````

**Comment by andreknieriem** [comment]
Thanks. I used your code and moved the prevent defaults to only mouse events. That should do the trick.
