### ISSUE TITLE
Global is not defined

### ISSUE THREAD

**Issue by SergeyOvsyannikov** [andreknieriem/simplelightbox#243]
Hello,
I saw the same issue, https://github.com/andreknieriem/simplelightbox/issues/211
But that solution doesn't work for me
I use `simple-lightbox.esm` and `esbuild` for building.
So, when I write `const global = window`, or `window.global = window` - doesn't matter.
Firstly `Esbuild` is adding `simple-lightbox.esm`, and then my variable.
In my file:
```
window.global = window;
import SimpleLightbox from "simplelightbox/src/simple-lightbox";
```

In output file smthing like this:
```
var simple_lightbox_esm_default = SimpleLightbox;
global.SimpleLightbox = SimpleLightbox;

//begin of my file
window.global = window;
```

In browser: `global is not defined at simple-lightbox.esm.js:1379`

Thank you.

**Comment by SergeyOvsyannikov** [comment]
Works for me, when i do `window.global = window` in other file and import that before import simpleLightbox

**Comment by howdu** [comment]
I was getting the same error and fix by using `require` instead of import.

`require('simplelightbox');`
