### ISSUE TITLE
Is there a "goTo" method?

### ISSUE THREAD

**Issue by TheCodeBoat** [andreknieriem/simplelightbox#245]
Is there a goto method or any other way to start the gallery at a specific index?

**Comment by andreknieriem** [comment]
Hi. you can use the open method. You habe to pass the element to open, not the index. 

open | Opens the lightbox with a given Element
-- | --

**Comment by TheCodeBoat** [comment]
Hi andre! - Yes, it worked! Thank you!
However, it's not that clearly noted in the documentation. 
Would be good if you mention that it's not just the "given" element, but the "starting/first" element of the gallery as well.
