### ISSUE TITLE
Customization options to achieve more immersion + Some interaction improvements

### ISSUE THREAD

**Issue by porg** [andreknieriem/simplelightbox#248]
Dear maintainer,

ℹ️ There is a ready-made Wordpress plugin [Responsive Gallery Grid](https://wordpress.org/plugins/responsive-gallery-grid/) which incorporates your SimpleLightBox!

👍 I gave it an [enthusiastic review in the Wordpress plugin section](https://wordpress.org/support/topic/clean-elegant-timeless-look-feel-immersion-interactions-could-improve/). I recommend that you read it, because the compliments to a large degree also concerns your SimpleLightBox! 👌🙂 

❓ I also put together a [compilation of feature proposals in the Wordpress plugin section](https://wordpress.org/support/topic/feature-proposals-for-perfect-interactions-immersion-factor-customizable/) for more customization options to achieve more immersion + some interaction improvements + minor glitches/bugs I noticed.

**Followup:**
- Could you please chime into the discussion over there on Wordpress.org?
- Or copy over the parts which you would like to address into this issue here, or chunk them up into followup issues, if you deem that the right way?

Regards, porg

**Comment by andreknieriem** [comment]
Hey. So what should I do?

**Comment by porg** [comment]
Hi, glad to get a first reaction. I updated my initial post. What would be great to do is in the "Followup" section.
I'm not clear how the work distribution between the SimpleLightBox library and the Wordpress plugin integration would be, but assume that all functionality would need to be in SimpleLightBox and the Wordpress plugin is mainy configuration of it and some wrapping. But as I do not know how this works  my proposed followup was quite open and not more concrete. I guess it would need some coordination between you and that Wordpress plugin author.

**Comment by porg** [comment]
* We could also hold a videocall at a time of your liking and I demonstrate the issues to you.  And from the reached understanding as a followup I could put that into Github issues for you.
* Or I could record a video demonstration for you and upload/link it here.
