### ISSUE TITLE
disableScroll option does not work

### ISSUE THREAD

**Issue by sharaputo** [andreknieriem/simplelightbox#249]
disableScroll option is set to true by default, but it does not work even in case I set it to true in options. Page is scrolling behind.

**Comment by andreknieriem** [comment]
Does this happen on the documentation page aswell? https://simplelightbox.com/ I cannot reproduce this on windows right now.

**Comment by sharaputo** [comment]
Yes. I am running macos Big Sur now and the problem is still here. I’ve checked Mozilla and Safari, same thing.

**Comment by andreknieriem** [comment]
Should be fixed in 2.8.1
