### ISSUE TITLE
if click previous

### ISSUE THREAD

**Issue by andrconstruction** [andreknieriem/simplelightbox#25]
Hi again :-)  Thanks for your application, it is a best what I found for my goals. 
I found a little bug
If image doesn't exist and I click on the left arrow(prev), images switches to right always but I think it should switches to left with a skipping non existing images

**Comment by andreknieriem** [comment]
Hey, thats a really special and rare case, but I will see what I can do.

**Comment by andreknieriem** [comment]
Fixed in source. Will be released soon.
