### ISSUE TITLE
get the current slide index ??

### ISSUE THREAD

**Issue by KarimAhmed-23** [andreknieriem/simplelightbox#251]
hi , Great job my bro about this wonderful library.
how I get the current slide index .
I use this library with the Slick library and I want to get a current slide index to pass it to (slickGoTo) Slick  method.

like this:

        let gallery = new SimpleLightbox('.gallery a');
        gallery.on('changed.simplelightbox', function () {
            
          var current_slide = gallery.currentSlide()  // this function that I mean how get;
	      var slide_index = current_slide.el.dataset.slickIndex;
          $('.slick-slider').slick('slickGoTo', slide_index);
            
        });

**Comment by andreknieriem** [comment]
You can now use gallery.getLighboxData()
