### ISSUE TITLE
@media screen and zoom: 120%; causes issue

### ISSUE THREAD

**Issue by Meister1977** [andreknieriem/simplelightbox#252]
Hi,

I am trying to add a webpage where we dynamically resize the full content if the screen is big with the code bellow. It causes that the images don't appear in the good position. Do you have any idea how to solve this?

```
@media screen and (min-width: 1200px) {
  body {
    zoom: 120%;
  }
```

**Comment by andreknieriem** [comment]
Sorry, but I will not make a fix for a css zoom, as this destroys many thinks.
