### ISSUE TITLE
Failed to execute 'getComputedStyle' on 'Window': parameter 1 is not of type 'Element'

### ISSUE THREAD

**Issue by blasnavarromir** [andreknieriem/simplelightbox#253]
Hi, I'm opening simplebox inside a Bootstrap 4 Modal and even though it's working fine, it's throwing this error.
If I use it outside the Modal there is no error.
I think it fails trying to calculate the height of the modal but I don't know how to solve it.
Any idea?
Thanks!

**Comment by andreknieriem** [comment]
Do you have a link where I can see it? Cannot repdroduce.

**Comment by andreknieriem** [comment]
Closed because of inactivity
