### ISSUE TITLE
Things go wrong when switching photos quickly

### ISSUE THREAD

**Issue by fpartl** [andreknieriem/simplelightbox#255]
When switching photos slowly using the navigation buttons or arrow keys on the keyboard, the lightbox works as expected. 

But when I quickly switch the photo at least twice, the simplelightbox starts working wrong. The next time I switch the photo, the current photo is only shifted slightly to the side. When I click the navigation button again, the next picture loads, but one picture is skipped.

I am using version 2.10.0. You can see it here on my [website](https://frantisekpartl.cz/#gallery).

**Comment by andreknieriem** [comment]
I can reproduce this. Thanks for reporting. Will take a look

**Comment by fpartl** [comment]
It works like a charm now, thank you!

https://frantisekpartl.cz/

**Comment by andreknieriem** [comment]
Glad to hear :)
