### ISSUE TITLE
Hiding the navigation button at the end of an album

### ISSUE THREAD

**Issue by fpartl** [andreknieriem/simplelightbox#256]
Hello, 

I have a small suggestion for improvement.

If I go through the entire photo album (specified by the `rel` attribute) and the `loop: false`, the right navigation button is still visible, but no action is performed when clicked. It would be a nice feature if the corresponding navigation button was hidden when being on the outermost photo.

Thank you!

**Comment by andreknieriem** [comment]
Good point.

**Comment by andreknieriem** [comment]
Was in the code, but there was an error. Fixed it
