### ISSUE TITLE
Apply SimpleLightbox to dynamically generate gallery

### ISSUE THREAD

**Issue by alexwenbj** [andreknieriem/simplelightbox#257]
Hi,first of all, thank you for your great job.
I wonder this plugin is suitable for the dynamically generate gallery, for example,  when the user click a button,then the page pull data from server to create the gallery, is it possible apply it to this gallery? I can't make it work.

**Comment by andreknieriem** [comment]
Hey. Just refresh your instance should work. See https://github.com/andreknieriem/simplelightbox#public-methods

```javascript
let gallery = new SimpleLightbox('.some-element a', { });

// some ajax stuff is going on and finished
gallery.refresh(); 
```

**Comment by alexwenbj** [comment]
@andreknieriem Great,Thank you.
