### ISSUE TITLE
Background overlay blink glitch on lightbox close

### ISSUE THREAD

**Issue by maxratajczak** [andreknieriem/simplelightbox#258]
Hello,

First of all great library, it's exactly what I was looking for - a simple, minimal, easy to implement lightbox. The only thing that really bothers me is the overlay stutter when closing the light box.

If you change the .sl-overlay background color to black, and then change the fadeSpeed to 1000 you will see this very clearly.
When you close the lightbox there is a split second where the overlay disappears and then returns. It removes the "smoothness" of the transition.

Is there any way I can prevent this from happening?

**Comment by andreknieriem** [comment]
Hey I will take a look. Did you change the opacity of the overlay? I see I've hardcoded 0.7 to the overlay in my script. Maybe this can cause issues.

**Comment by maxratajczak** [comment]
When the opacity stayed at 0.7 the bug still occurred, but I did mess around with the opacity and I found it actually made the bug a bit worse. When I set the opacity to 0.5 or 0.6 the flicker would happen on lightbox open **and** close. I also noticed that when I changed the opacity to 1, the flicker wouldn't happen, so this bug possibly has something to do with the opacity.

**Comment by andreknieriem** [comment]
Hey. This should work now ;)

**Comment by maxratajczak** [comment]
Yes!! Thank you!! It works perfectly now. Amazing library, great job :)
