### ISSUE TITLE
Mouse zoom centering

### ISSUE THREAD

**Issue by scrollable-sidebar** [andreknieriem/simplelightbox#264]
If the clickable thumbnail is below the fold, then once enlarged, zooming in with the mouse wheel does not zoom centered on the cursor.

This can be reproduced by
- visiting the simplelightbox.com home page
- zooming in the browser sufficiently that the yellow thumbnail is pushed down the page, below the fold
- scrolling down to the yellow thumbnail and clicking it
- positioning the mouse cursor over the top left corner of the image, and zooming in with mouse wheel

The zoom in will not be centered on the location of the mouse cursor, but centered on a lower position.

If you then position the mouse pointer over the bottom left corner and zoom in, you can see the difference.

(Alternatively you can reduce the height of the browser window such that the yellow thumbnail is below the fold).

**Comment by scrollable-sidebar** [comment]
Thank you for fixing it, you're a star!

**Comment by curtiswallen** [comment]
Maybe related to this(?), I'm having a zoom issue as well. 

I'm using simplelightbox here: https://williampowhida.com

If you click the first image and use the scroll wheel to zoom in and out, it works as expected. But if you scroll to the right and click on an image further in on the page, then try to zoom with the scroll wheel, it always pins to the right edge on zoom in and then the left edge on zoom out.

Sorry if inappropriate to add this to this previously squashed bug, but seems similar enough to keep in context. Let me know if better to open a new issue! And thank you for all your work on simplelightbox!!
