### ISSUE TITLE
SimpleLightbox and React Guide

### ISSUE THREAD

**Issue by stephania2405** [andreknieriem/simplelightbox#265]
Hi,

Can anyone please guide me in regards to how I can use SimpleLightbox with ReactJS?

So far I installed the library with `npm install simplelightbox`, I added `import SimpleLightbox from "simplelightbox";` in my functional component but I don't know what else exactly I should be doing.

Thank you in advance

**Comment by andreknieriem** [comment]
Hey. I do not use react and I am not able to tell you something about this. There is also an issue with that topic. Maybe you can use this:
https://github.com/andreknieriem/simplelightbox/issues/224

I close this for now.
