### ISSUE TITLE
Uncaught TypeError: Cannot call a class as a function

### ISSUE THREAD

**Issue by beckbailey** [andreknieriem/simplelightbox#269]
Uncaught TypeError: Cannot call a class as a function error is present in the console log and I can't seem to clear it. I have a simple set up as instructed.

**Comment by andreknieriem** [comment]
Hey do you have a public link?

**Comment by beckbailey** [comment]
https://evergreenpodcasts.com/sleepover-cinema

**Comment by andreknieriem** [comment]
Is this a problem with the lightbox? This is minified and I can't see what the problem is. The lightbox at the buttom just works fine.

**Comment by beckbailey** [comment]
It works ok but I have the error I mentioned in my original post in the console log and can't seem to clear it. Sent from my T-Mobile 5G Device
-------- Original message --------From: Andre Rinas ***@***.***> Date: 6/9/22  3:30 AM  (GMT-05:00) To: andreknieriem/simplelightbox ***@***.***> Cc: beckbailey ***@***.***>, Author ***@***.***> Subject: Re: [andreknieriem/simplelightbox] Uncaught TypeError: Cannot call a class as a function (Issue #269) 
Is this a problem with the lightbox? This is minified and I can't see what the problem is. The lightbox at the buttom just works fine.
