### ISSUE TITLE
No more picture visible after sliding a picture outside a brower

### ISSUE THREAD

**Issue by stevevanhoyweghen** [andreknieriem/simplelightbox#27]
Hi,

Good clean lightbox. Thanks!!!

I will use it in my photography portfolio site in combination with http://miromannino.github.io/Justified-Gallery/. Unfortunately I have one annoying issue found during testing.

I use simplelightbox on a laptop/desktop with a browser when testing. If the browser is not maximized, and I slide outside the browser window, simplelightbox is closed. This is not the real issue (however it would be nice to prevent it if possible).

Next I click on a random picture of the collection to show with simplelightbox. As a response I get the arrows, X-symbol, and the numbering, but **no picture** appears. However if I click one of the navigation arrows the next/previous picture is shown and everything is back to normal again.

I have the same phenomena with IE, Chrome and Firefox.

Regards,

Steve

**Comment by andreknieriem** [comment]
Hi Steve, thanks for your feedback, I will take a look, what's the problem.

**Comment by andreknieriem** [comment]
Fixed in source code. Will be online soon.

**Comment by stevevanhoyweghen** [comment]
Hi,

Tested and OK,
Thanks!

Steve
