### ISSUE TITLE
Not working with infinite scroll ?

### ISSUE THREAD

**Issue by RolandTi** [andreknieriem/simplelightbox#270]
Hello ! 
I've been using SimpleLightBox with "Catch Infinite Scroll" or "WP EasyScroll Posts" and I'm having the same issue.

All pictures loaded through the infinite scroll script doesn't have any ligthbox.
It's working only on pictures from the main page.

I'm almost sure there is a solution to analyze the page again after each new loaded post, but I don't know how :)

Any clue ? Thanks !

**Comment by andreknieriem** [comment]
You need to call the refresh method of the lightbox. I don't know if you can hook to the scroll plugin and reload the lightbox.
`
refresh | Destroys and reinitializes the lightbox, needed for eg. Ajax Calls, or after dom manipulations
`

**Comment by RolandTi** [comment]
> You need to call the refresh method of the lightbox. I don't know if you can hook to the scroll plugin and reload the lightbox. `refresh | Destroys and reinitializes the lightbox, needed for eg. Ajax Calls, or after dom manipulations`

Thank you :)
