### ISSUE TITLE
Not compatible with latest themes

### ISSUE THREAD

**Issue by ddegner** [andreknieriem/simplelightbox#271]
When using the default "Twenty Twenty-Two" theme simplelightbox doesn't work. When an image is clicked, the browser opens the media file instead of the lightbox.

I tried this on a vanilla install of the latest WP, PHP 7.8, only simplelightbox installed. I placed one image on the post with the link to "Media File."

I also tried the popular [Frost](https://frostwp.com) theme, and simplelightbox doesn't appear to work with it. But it does work with the Twenty Twenty theme on the same install.

Unfortunately, I don't know enough to fix the problem, just point out that in future themes, there might be an issue.

**Comment by andreknieriem** [comment]
Work on it in the wordpress support section. This is the pure JS version
