### ISSUE TITLE
Plugin not fire up when load custom url whith #pid=1

### ISSUE THREAD

**Issue by biznesmen4d** [andreknieriem/simplelightbox#272]
Hello

When i type custom url to browser adress for example  https://site.ru#pid=1 history don't work and image in gallery not open, it just open https://site.ru

**Comment by biznesmen4d** [comment]
And when slider is open, if i change the number of slide it does not back or move forward

**Comment by Mtillmann** [comment]
Hi, can you please provide some example code for the issue? Thanks

**Comment by biznesmen4d** [comment]
For example, adress https://simplelightbox.com/       If enter https://simplelightbox.com/#pid=1 - 1 slide not fire up. If open slider and change numbers, its also not change slides to back or forward item

**Comment by andreknieriem** [comment]
Hi. That is not the way the lightbox works. The hash only changes the history in the browser to prevent the user from going back in history with the back button, especially on mobile devices. Some users click the back button if the lightbox is open to close it and the hash will prevent that. It is not an loader for an image. If you need that function, you can easy write it yourself. Feel free to ask for help here.

**Comment by biznesmen4d** [comment]
If it not take so many your time, please tell me how i can fix this behavior for myself?
