### ISSUE TITLE
Make it work with a single image as well

### ISSUE THREAD

**Issue by sam365724** [andreknieriem/simplelightbox#273]
The lightbox does not fire/work if only one image is found by the passed selector, can this be configureable?

`new SimpleLightbox('div.oneimagegallery > img')`

**Comment by andreknieriem** [comment]
Hey. Can you tell me what was the problem? Maybe some other user has some problems too in the future.

**Comment by sam365724** [comment]
It was another root cause: The lightbox was not refreshed after page navigation, so i added a .refresh() call to the app.
