### ISSUE TITLE
Lightbox is not able to handle this type of URL image resource

### ISSUE THREAD

**Issue by javac9** [andreknieriem/simplelightbox#274]
Hi,

While `img` is able to show thumbnails from a URL resource like this: `http://example.com/gallery/main.php?g2_view=core.DownloadItem&g2_itemId=12345`, the wrapping link element is not able to load large (in my case, the same) image from such a URL.

Is there a solution to this? I really like the Lightbox and would love to see this enhancement in the next release!

**Comment by andreknieriem** [comment]
You need to fileExt:false as option.
