### ISSUE TITLE
Passive listener for Google PageSpeed

### ISSUE THREAD

**Issue by mksh-su** [andreknieriem/simplelightbox#277]
Hello,

I've seen there were similar issues (e.g #240) which are closed, but for some reason I still get the same error with passive listeners and scrolling performance on Google PageSpeed. I use the latest version of Simple Lightbox (2.10.2). Here's [the report](https://pagespeed.web.dev/report?url=https%3A%2F%2Finsider-week.com%2Fde%2F), if interested.

<img width="958" alt="Screenshot 2022-09-08 at 16 25 31" src="https://user-images.githubusercontent.com/26872910/189148075-30c0035f-cde7-44aa-9d63-83c904cb5700.png">

What can be done about this?

Thank you!

**Comment by andreknieriem** [comment]
I will take a look. Thanks for the hint.

**Comment by andreknieriem** [comment]
Ok this is absolutely annoying. 
![Bildschirmfoto 2022-10-13 um 07 01 46](https://user-images.githubusercontent.com/4500367/195505950-0a5af703-425e-46d0-82e5-66afe00a51ee.png)
The passive listener is on every touch event. But it seems, this is not enoug anymore. Will take some time to check what this means

**Comment by andreknieriem** [comment]
Ok they mean scroll events in addition to touch events. New version will come today

**Comment by mksh-su** [comment]
Thank you very much!
