### ISSUE TITLE
Initialization and events don't seem to work according to documentation?

### ISSUE THREAD

**Issue by strlns** [andreknieriem/simplelightbox#278]
Hi, first of all, thanks for the library.

I have some issues using this without jQuery. The documentation on initialization and events seems to be wrong.

**Intialization:**
Using 
`new SimpleLightbox('.some-element a', { /* options */ });` as specified in the docs causes the lightbox to fail and the selector from the first argument is spread to the instances options object:
```
options: {
0: ".",
1: "s",
2: "o",
3: "m",
4: "e",
5: "-",
6: "e",
7: "l",
8: "e",
9: "m", /*...*/
afterClose: null
```

However, passing a selector, array or NodeList as property `elements` in the options object works fine:
`new SimpleLightbox( {elements: selectorOrIterableOfElements});`

**Events:**
According to the docs, this should work:
```
const gallery = new SimpleLightbox('.gallery a');
gallery.on('show.simplelightbox', function () {
```
It doesn't for me (on is not a function).

Listening to these events using a native event listener directly does not work either.
The lightbox has an `addEvent` method on its prototype, but it seems to be for internal use as using it causes the lightbox to stop working for me.

**Comment by andreknieriem** [comment]
Hi there. Are you sure using the latest version and this plugin? There are some lightboxes with the same name. If you download this repository as a zip and open demo/index.html you can see at the buttom at line 788 that the initialisation does work just fine and if you change the code to:

```javascript
let $gallery = new SimpleLightbox('.small-demo a', {});
$gallery.on('show.simplelightbox', function () {
    console.log('event testing');
});
```

**Comment by strlns** [comment]
My bad. You are completely right – my (embarassing) mistake, I was in a hurry and confused your package with a very similar one.

Sorry and thanks for the quick response!
