### ISSUE TITLE
Lightbox will not appear on firefox

### ISSUE THREAD

**Issue by JTWebStudio** [andreknieriem/simplelightbox#28]
Hello 

My lightbox works perfectly fine on all browers beside firefox. Any ideas ?

**Comment by andreknieriem** [comment]
Hi, can you tell me on which system and which version you use? No problems here on OSX and Windows 10 with Firefox

**Comment by JTWebStudio** [comment]
I am using windows 8.1 with the latest version of the plugin. Firefox browser is also up to date.
Here is my code http://pastebin.com/ar7g5R67

**Comment by andreknieriem** [comment]
Hi, in your code you include bootstrap and jquery 2 times. Maybe that's an error. Without the images and the files I can't get your code working. Maybe you have an online example? I can't reproduce an error in any of my browsers.

**Comment by andreknieriem** [comment]
No answer sind over 2 weeks and cannot reproduce, so close.
