### ISSUE TITLE
Issue with two links to the same image

### ISSUE THREAD

**Issue by t3brightside** [andreknieriem/simplelightbox#282]
Example:
```html
<div class="gallery">
  <a href="img/full/01.jpg"><img src="img/thumb/01.jpg" alt="" title="" /></a>
  <a href="img/full/01.jpg"><img src="img/thumb/02.jpg" alt="" title=""/></a>
  <a href="img/full/03.jpg"><img src="img/thumb/03.jpg" alt="" title=""/></a>
</div>
```
This results second thumbnail link opening the image in new tab not in lightbox and lightbox shows there's only two images in set.

There can be a use case where there is different thumbnails but linking to the same image.

**Comment by t3brightside** [comment]
Silly me, just had to turn off uniqueImages :)

**Comment by mendhak** [comment]
Thanks that's just what I needed.  I was trying to lightbox the same image twice on the same page.
