### ISSUE TITLE
html class with trailing whitespace creates an error

### ISSUE THREAD

**Issue by MVogge** [andreknieriem/simplelightbox#284]
When a html class attribute has a trailing whitespace, there is an error thrown due to the selector generated by _generateQuerySelector()_ being invalid.

<img width="323" alt="image" src="https://user-images.githubusercontent.com/34127888/203965412-bba46ce6-c43e-495a-898e-88cce8d6da16.png">
<img width="600" alt="image" src="https://user-images.githubusercontent.com/34127888/203966414-dd0e8769-cc21-4bd3-b32e-6b88b29d4ae4.png">

Mind the . before the pseudo-selector in the highlighted area of the error message.

I also created #283 as an attempt to fix it

----

I'm using the latest version 2.11.0

**Comment by andreknieriem** [comment]
Fixed. Thanks for the PR
