### ISSUE TITLE
Events is not working on Vanilla Javascript

### ISSUE THREAD

**Issue by judevs** [andreknieriem/simplelightbox#285]
I can't use the events with Vanilla Javascript, I'm getting an error
![image](https://user-images.githubusercontent.com/32464575/204036724-520e9149-ca13-4c47-873f-ae81dce0dd33.png)

I'm using it correctly, right? I tried removing `simplelightbox` in the event but it still returning the same error.
```
let lightbox = new SimpleLightbox('.featured-img a', {});
lightbox.addEventListener('shown.simplelightbox', function() {
    console.log('test 1');
}, false);
```

**Comment by judevs** [comment]
I got it, so based on the documentation, use the declared simplelightbox variable to add an event, for this example I used `lightbox` so I went ahead `lightbox.addEventListener` but it doesn't work that way, you need to add the event to the **HTML ELEMENT** itself not the declared lightbox variable for it to work, the code below works fine for me. 


```
let featuredImg = document.querySelector('.featured-img a'); // one <a> only not an array of <a> tag
let lightbox = new SimpleLightbox(featuredImg, {});
featuredImg.addEventListener('shown.simplelightbox', function() {
    console.log('test 1');
}, false);
```


but the owner/author should at least fix the misunderstanding on the documentation
![image](https://user-images.githubusercontent.com/32464575/204924986-a788c082-f4bf-4710-b3ea-87d75fbd4517.png)

**Comment by andreknieriem** [comment]
Hi. Sry for the late response. You didn't use the on Method "on" from the lightbox. 

```
let gallery = new SimpleLightbox('.gallery a');
gallery.on('show.simplelightbox', function () {
	// do something…
});
```
This will work in vanilla Javascript
