### ISSUE TITLE
Syntax for options (question)

### ISSUE THREAD

**Issue by lorembolo** [andreknieriem/simplelightbox#29]
Hi, 

I'm trying to use this plugin, wich looks ghreat. 
I'm not really good at JS so, I wonder what is the syntax for passing options to Simplelightbox ? 

For example, I would like to change the close text. Following code is not working

var gallery = $('.galerie a').simpleLightbox(closeText : 'close');
	});

Any idea ? 
Thx

**Comment by andreknieriem** [comment]
Hi you closed the issue. Do you still need help? If yes the syntax is this way:

var gallery = $('.galerie a').simpleLightbox({
  closeText : 'close',
  otherOption: true,
  ... : ...
});
