### ISSUE TITLE
Bug: Lightbox only works once, clicking image again results in error

### ISSUE THREAD

**Issue by mendhak** [andreknieriem/simplelightbox#292]
Problem: The lightbox only works once.  Clicking the image again results in an error and lightbox without image. 

Tested in Firefox and Edge. 

Steps to reproduce: 

1. Go to https://simplelightbox.com/
2. Click one of the images 
3. Close the lightbox (eg press Escape)
4. Click the image again

What you see is a large lightbox overlay without the image.  

![image](https://user-images.githubusercontent.com/746276/212010463-6122e215-f6fb-4d38-b6c2-7c68edc99900.png)

In the console this error appears:

```
Uncaught TypeError: i is null
    value https://cdn.jsdelivr.net/gh/andreknieriem/simplelightbox@master/dist/simple-lightbox.min.js?v2.11.0:1
    value https://cdn.jsdelivr.net/gh/andreknieriem/simplelightbox@master/dist/simple-lightbox.min.js?v2.11.0:1
    i https://cdn.jsdelivr.net/gh/andreknieriem/simplelightbox@master/dist/simple-lightbox.min.js?v2.11.0:1
simple-lightbox.min.js:1:44012
    value https://cdn.jsdelivr.net/gh/andreknieriem/simplelightbox@master/dist/simple-lightbox.min.js?v2.11.0:1
    value https://cdn.jsdelivr.net/gh/andreknieriem/simplelightbox@master/dist/simple-lightbox.min.js?v2.11.0:1
    i https://cdn.jsdelivr.net/gh/andreknieriem/simplelightbox@master/dist/simple-lightbox.min.js?v2.11.0:1

```

**Comment by andreknieriem** [comment]
Hi. Thanks. Will fix this immediately

**Comment by mendhak** [comment]
Hey there, thanks for looking, but I'm still seeing the problem on the home page, are you seeing the same?  It definitely looks like v2.12.1 the latest version.   Or did I test too quickly, should I wait a bit?  

![image](https://user-images.githubusercontent.com/746276/212028021-8576c182-d482-4123-b322-ba62b1783075.png)

**Comment by andreknieriem** [comment]
Jsdelivr is not ready with latest version. The js gets loaded extern. You need to wait a little bit or download the latest release and try the demo/index.html

**Comment by mendhak** [comment]
It works now, thanks!
