### ISSUE TITLE
Not working close and naviations buttons

### ISSUE THREAD

**Issue by vanaveno** [andreknieriem/simplelightbox#293]
Hi
I don't know how to set up litebox correctly, I downloaded the  Version 2.12.1, simple-lightbox.js and after code                     

`<div class="gallery border">
   <a class="col-lg-2 col-12 pic p-1 float-lg-left d-b" href="image1" >
                                        <img class="wmax100"
                                            src="image1" />
                                    </a>
   <a class="col-lg-2 col-12 pic p-1 float-lg-left d-b" href="image2" >
                                        <img class="wmax100"
                                            src="image2" />
                                    </a>
                    </div>`

                <script>
                
let gallery = new SimpleLightbox('.gallery a');

                </script>
                
the picture is opening but not working buttons like close next and preview, where am I making mistake?
Thanks
Vana

**Comment by andreknieriem** [comment]
Seems like an error appeared. Which file do you use? Everything looks like this should work.

**Comment by iamcaptaincode** [comment]
I'm seeing this same error message.

**Comment by Duod-Notyap** [comment]
Not sure if this has been resolved but I just had this exact issue due to using the wrong version. I was using the 
`simple-lightbox.min.js` 
instead of the (correct) jQuery compatible 
`simple-lightbox.jquery.min.js`
Swapping the files resolved the issue.

**Comment by michaelmannucci** [comment]
Did you guys figure this out? What _Duod-Notyap_ suggested did not work for me.

**Comment by andrey-yumasoft** [comment]
I was able to make it work by providing _captionSelector: 'self'_ option:

`.simpleLightbox({  captionSelector: 'self' })`
