### ISSUE TITLE
simpleLightbox.js:8 Uncaught TypeError

### ISSUE THREAD

**Issue by wordica** [andreknieriem/simplelightbox#297]
Uncaught TypeError: Cannot set properties of undefined (setting 'SimpleLightbox')

Works but always I see this error in console.

    if (typeof define === 'function' && define.amd) {
        define([], factory);
    } else if (typeof module === 'object' && module.exports) {
        module.exports = factory();
    } else {
        root.SimpleLightbox = factory(); /// this line
    }

**Comment by andreknieriem** [comment]
Sorry I need more information. Which file do you use exactly in which browser etc. Do you have a visible test page?

**Comment by andreknieriem** [comment]
close with because of no response
