### ISSUE TITLE
Don't output markup if not initialized

### ISSUE THREAD

**Issue by slavanga** [andreknieriem/simplelightbox#3]
The following markup will be generated just by including the plugin with no initialization:

```html
<div class="sl-overlay"></div>
<div class="sl-wrapper simple-lightbox">
	<div class="sl-image"></div>
	<button class="sl-close">X</button>
	<div class="sl-navigation">
		<button class="sl-prev">←</button>
		<button class="sl-next">→</button>
	</div>
	<div class="sl-spinner"><div></div></div>
</div>
```

**Comment by andreknieriem** [comment]
Hi @slavanga, you mean, that this markup is already in dom, even if you don't open a lightbox? Do you think that is a problem? Additionally should the markup be removed, if you close the lightbox?

**Comment by slavanga** [comment]
In my opinion the markup should only exist in the dom while the lightbox is open.

**Comment by andreknieriem** [comment]
Hey, I released a new version with your enhancement! Thanks for feedback ;)
