### ISSUE TITLE
Error when opening the lightbox the second time while using the download option.

### ISSUE THREAD

**Issue by axl4life** [andreknieriem/simplelightbox#307]
I get the following error when I try to open the lightbox the second time: Uncaught TypeError: Failed to execute 'appendChild' on 'Node': parameter 1 is not of type 'Node'.
this.options.download && this.domNodes.wrapper.appendChild(this.domNodes.download)

I fixed it by adding another test:
this.options.download && this.domNodes.download && this.domNodes.wrapper.appendChild(this.domNodes.download)

**Comment by andreknieriem** [comment]
Thanks. Added that fix
