### ISSUE TITLE
overflow:scroll 

### ISSUE THREAD

**Issue by enkia** [andreknieriem/simplelightbox#308]
I'm trying to enable the ability to scroll up or down if an image's height exceeds viewport. I've tried modifying via overflow:scroll but no luck. Can you provide any tips? 

```
new SimpleLightbox('.lightbox', {
  loop: false,
  nav: false,
  showCounter: false,
  overlayOpacity: 0.95,
  widthRatio: 0.9,
  heightRatio: 1.5,
  doubleTapZoom: 1,
  scrollZoom: false
});
```

**Comment by andreknieriem** [comment]
User the option is disableScroll and set it to false.
