### ISSUE TITLE
Unable to preventDefault inside passive event listener invocation.

### ISSUE THREAD

**Issue by SmatterDaniel** [andreknieriem/simplelightbox#310]
I get this error in the console after opening an image in the lightbox and then zooming in or out:

> simple-lightbox.jquery.min.js?ver=2.12.1:1 Unable to preventDefault inside passive event listener invocation.
> (anonymous) @ simple-lightbox.jquery.min.js?ver=2.12.1:1

The zooming functionality itself works fine, however.

**Comment by andreknieriem** [comment]
Thanks for mention! Fixed it in the new version 2.13.0
