### ISSUE TITLE
Overlay stays on the page while lightbox is closed

### ISSUE THREAD

**Issue by IhorKulinskyi** [andreknieriem/simplelightbox#312]
Hello, I have a problem, when opening a new lightbox after closing previous, the overlay doesn't go away, and you should click to close it. If you open and close the lightbox n-times there would be n overlays on the page.

**Comment by andreknieriem** [comment]
Hi. When did this happen. I cannot reproduce this.

**Comment by andreknieriem** [comment]
Ok, I see you initialize a new Lightbox everytime someone clicks on a Gallery-List-Item. So you add every listener again and again until you have tons of lightboxes. That's not the way to do this. You can do multiple things. 
1. Initilize it once and use the rel attribute to group them. 
2. Destroy the lightbox first when click on that gallery item.

**Comment by IhorKulinskyi** [comment]
Thank you!

Чт, 30 марта 2023 г. в 07:31, Andre Rinas ***@***.***>:
