### ISSUE TITLE
XSS Vulnerability when caption source is user provided

### ISSUE THREAD

**Issue by splitbrain** [andreknieriem/simplelightbox#317]
The `setCaption()` method uses  the `.innerHTML` property to set the caption of a displayed image. If the lightbox script is used to display user provided images with the caption either being directly user supplied or extracted from EXIF data, this will allow for injecting arbitrary HTML (and script tags).

I would suggest to either always use `.innerText` or at least make the behaviour customizable.

**Comment by Mtillmann** [comment]
I disagree that this is an XSS vector as it relies on the integration to pass unsanitized content into the method. I agree that the api should allow for more control of dom handling and that the content should be inserted as text by default, only as html if  explicitly   or globally (options) enabled

**Comment by Mtillmann** [comment]
@splitbrain please see the referenced fork/pr for a new option that lets you modify the content insertion behaviour
