### ISSUE TITLE
Why performing another select query ?

### ISSUE THREAD

**Issue by K20** [andreknieriem/simplelightbox#32]
Hello, I tried your library and it works pretty well, but I have an issue on a way you handle the jquery objects.

Why don't you iterates over the object passed in your jquery function instead of performing a new jquery selection ? 

Line 77 : 

`objects = $( this.selector, this.context ),`

Why not using directly the objects array of the jquery function ? 

` this.each(function() { var $this = $(this); /*...*/  });
`

Thank you.

**Comment by andreknieriem** [comment]
Hi, this was an Pull request for multiple lightboxes on one page and it worked, so I used it. Can you explain what do you mean exactly? Sorry I don't get what you want.

Thanks!

**Comment by andreknieriem** [comment]
I understand, in Line 77 I can just use `objects = this,` and nothing else. Thanks I just fixed it.

**Comment by K20** [comment]
Thanks, and sorry for my english !
