### ISSUE TITLE
Images are reloaded frequently

### ISSUE THREAD

**Issue by noahfpf** [andreknieriem/simplelightbox#321]
When the lightbox is open, it appears to request the same image files repeatedly.  See the screenshot for an example in which I did the following:
1. Visited https://simplelightbox.com/
2. Clicked on an image thumbnail
3. Clicked the next button a couple times.  Each navigation click reloaded three images (the current, the next, and the previous).

![Repeat image requests](https://github.com/andreknieriem/simplelightbox/assets/51243371/3d93bf49-b70a-498f-b191-60ad6b3a2d73)

This reloading occurs regardless of whether the `preloading` option is set to true or false.

Resizing the window also causes the current image to be reloaded.

Should the images be cached once they're first loaded to avoid the time delay and data transfer in reloading them?

Tested with:
- simplelightbox 2.14.2
- Chrome 117.0.5938.149 on macOS

**Comment by Mtillmann** [comment]
Hi @noahfpf , please uncheck the "disable cache" feature in your dev tools and try again. For me this does only happen while the dev tools are open. If in doubt try:

```shell
git clone git@github.com:andreknieriem/simplelightbox.git
cd simplelightbox
npm i http-server -g
http-server .
# open http://localhost:8080/demo
```
Then observe the actual requests being received by the server.

**Comment by noahfpf** [comment]
Oh, I see!  Thank you for the explanation, and for the library!
