### ISSUE TITLE
Lightbox opens href instead of lightbox in chrome

### ISSUE THREAD

**Issue by dinandmentink** [andreknieriem/simplelightbox#323]
On chrome only (firefox works fine) it opens the lightbox and then immediately navigates to the image. I can't seem to fix it. 

Live example, for example on my personal website: https://www.dinandmentink.nl/postits/4

This is the script I use to initialize the lightbox:

```javascript

import SimpleLightbox from "simplelightbox/dist/simple-lightbox.esm";

document.addEventListener("app-load", function () {
  document.querySelectorAll("[data-gallery]").forEach((elem) => {
    var selector = elem.getAttribute("data-gallery");
    var items = "[data-gallery~=" + selector + "] [data-gallery-item]";

    new SimpleLightbox(items, {
      history: false,
      fadeSpeed: 100,
      animationSpeed: 100,
    });

    // Remove default behaviour from a elements
    var items = "[data-gallery~=" + selector + "] a[data-gallery-item]";
    document.querySelectorAll(items).forEach(function(item) {
      item.addEventListener('click', function(event) {
        event.preventDefault();
        event.stopPropagation();
        return false;
      });
    });

    elem.removeAttribute("data-gallery");
  })
});
```

I tried fixing it by using preventDefault and stopPropagation, but no dice. Anyone run into this, any suggestions?  I really hope someone can shed some light on this, I have been breaking my head on it.

**Comment by Mtillmann** [comment]
Can you try and disable turbolinks and see if the problem persists? I'm pretty certain that this is not a issue with simplelightbox. I see that the lightbox opens before the location is changed to the image uri

**Comment by dinandmentink** [comment]
Yes, the lightbox does open before switching to a new page. 

Oh, yes, ofcourse. Let me try, it would be so obvious.

**Comment by dinandmentink** [comment]
Too bad. Disabling turbo on these links doesn't work. Neither does completely disabling turbo.

For some reason I can not reproduce it on localhost, to test it in development I have to add a fake domain to /etc/hosts. 

Anything else you can think of?

**Comment by Mtillmann** [comment]
no worries, I'll close this issue
