### ISSUE TITLE
Issue with activated history

### ISSUE THREAD

**Issue by SmokinB** [andreknieriem/simplelightbox#324]
If there is an anchor in the URL from history (for example #pid=1) and I perform a hard page reload (CMD+r), open the lightbox and close it again, an error is thrown on close:

Uncaught DOMException: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.

**Comment by andreknieriem** [comment]
Hi, which browser you are using? Cannot reproduce this on simplelightbox.com

**Comment by SmokinB** [comment]
Hello (-:

Chrome Version 118.0.5993.88 on MacOs

unfortunately I can't reproduce it on simplelightbox.com either.

This is the console output:

`simple-lightbox.min.js:1 Uncaught DOMException: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
    at i.<anonymous> (https://cdn.jsdelivr.net/npm/simplelightbox@2.14.1/dist/simple-lightbox.min.js:1:12633)
    at t (https://cdn.jsdelivr.net/npm/simplelightbox@2.14.1/dist/simple-lightbox.min.js:1:44131)
(anonymous) @ simple-lightbox.min.js:1
t @ simple-lightbox.min.js:1
requestAnimationFrame (async)
t @ simple-lightbox.min.js:1
requestAnimationFrame (async)
t @ simple-lightbox.min.js:1
requestAnimationFrame (async)
t @ simple-lightbox.min.js:1
requestAnimationFrame (async)
t @ simple-lightbox.min.js:1
requestAnimationFrame (async)
t @ simple-lightbox.min.js:1
requestAnimationFrame (async)
t @ simple-lightbox.min.js:1
requestAnimationFrame (async)
t @ simple-lightbox.min.js:1
requestAnimationFrame (async)
t @ simple-lightbox.min.js:1
requestAnimationFrame (async)
t @ simple-lightbox.min.js:1
requestAnimationFrame (async)
t @ simple-lightbox.min.js:1
requestAnimationFrame (async)
t @ simple-lightbox.min.js:1
requestAnimationFrame (async)
t @ simple-lightbox.min.js:1
requestAnimationFrame (async)
t @ simple-lightbox.min.js:1
requestAnimationFrame (async)
t @ simple-lightbox.min.js:1
requestAnimationFrame (async)
t @ simple-lightbox.min.js:1
requestAnimationFrame (async)
t @ simple-lightbox.min.js:1
requestAnimationFrame (async)
t @ simple-lightbox.min.js:1
value @ simple-lightbox.min.js:1
value @ simple-lightbox.min.js:1
(anonymous) @ simple-lightbox.min.js:1`

**Comment by Mtillmann** [comment]
please create a demo of the issue. It is very probable that there's an issue in your markup, unrelated to simplelightbox
