### ISSUE TITLE
Opening the lightbox from a modal window

### ISSUE THREAD

**Issue by jaroslavlibal** [andreknieriem/simplelightbox#325]
Hello,

I'm trying to integrate this library into my system, where I would like to open galleries from the Bootstrap 5 modal window.

But besides the z-index issue, which I can solve, I am concerned about these two things, probably both related to focusing:

1) After opening a link to a photo and every time I move to the next one, I get the "Uncaught RangeError: maximum call stack size exceeded." error. Unfortunately, to prevent this from happening, I have to set the modal's "data-bs-focus" attribute to "false", but this causes the modal window not to close with the keyboar or to set the simplelightbox "focus" to false, which is what I currently use.

2) Is there any way to get one press of the ESC key to close only the simplelightbox and not the modal, but to be able to close the modal with the ESC key when the simplelightbox is closed?

Thank you

**Comment by Mtillmann** [comment]
Hi @jaroslavlibal this is out of scope for this project. I think you'd be better off using [multíple modals](https://getbootstrap.com/docs/5.3/components/modal/#toggle-between-modals) and [bootstrap's carousel](https://getbootstrap.com/docs/5.3/components/carousel/). I am closing this issue

**Comment by jaroslavlibal** [comment]
I know the issue is closed, but for others who might have a similar problem to mine - I solved it as follows:

```javascript
var galleryModalEl = document.getElementById("gallery-modal");

let gallery = new SimpleLightbox('.gallery-photos a', {
    'focus': false
});

gallery.on('show.simplelightbox', function () {
    let galleryModal = bootstrap.Modal.getInstance(galleryModalEl);
    if (galleryModal !== null) {
        galleryModal._config.keyboard = false;
    }
});

gallery.on('close.simplelightbox', function () {
    let galleryModal = bootstrap.Modal.getInstance(galleryModalEl);
    if (galleryModal !== null) {
        galleryModal._config.keyboard = true;
    }
});
```

I'm not very experienced in javascript, so the code probably isn't pretty, but it works.
