### ISSUE TITLE
Preventing the showing lightbox

### ISSUE THREAD

**Issue by igieske** [andreknieriem/simplelightbox#327]
How can I prevent the opening of lightbox if it was a click with dragging? It is required when I use lightbox with sliding gallery. I already tried to use `'show.simplelightbox'` event with `event.preventDefault()` – it doesn't work.

**Comment by Mtillmann** [comment]
I believe this is out of scope for the project. However, if you've found a solution, feel free to share it here for others who might runi into a similar issue
