### ISSUE TITLE
No more dynamic content in lightbox?

### ISSUE THREAD

**Issue by jaywalker291** [andreknieriem/simplelightbox#328]
Previous versions I was adding HTML content to the lightbox dynamically, but now it seems this isn't possible? I updated simplelightbox to the latest version and it broke our site. 

This worked before:
```
simpleLightbox.open({
	content: '<iframe src="'+daSrc+'"></iframe>',
	elementClass: 'contact-lightbox'
});	
```

Now it throws error. How do I get the above working again? Is there no more "content" option?

**Comment by Mtillmann** [comment]
do you know version you used before the update?
