### ISSUE TITLE
Body tag styles leftovers

### ISSUE THREAD

**Issue by bbprojectnet** [andreknieriem/simplelightbox#33]
Could you clean up body element after lightbox closing? Currently this stays there: https://db.tt/WJpB7SpI and for example `overflow: auto` causes problems to any element which uses `position: sticky` on a page. A solution would be `overflow: initial` or simply removing styles after lightbox closing.

**Comment by andreknieriem** [comment]
Hi there, you are right. I've changed it to visible, which is the initial state. Removing all styles can produce some errors, if other scripts use styling on the body-tag, so thats not an option. Will be online within the next few minutes!

**Comment by bbprojectnet** [comment]
`visible` is not the initial state. Well, it is, but you can't know what a document's CSS is, so this change may cause problems too. I think the best solution would be to add a class (for example `simplelightbox-open`) to body while opening, and remove it while closing. And add attributes to the attached styles instead of adding them inline as it is now.

**Comment by andreknieriem** [comment]
Hi, thats true. I will do it this way.

**Comment by andreknieriem** [comment]
Finally fixed it the right way with new version!

**Comment by bbprojectnet** [comment]
Thx for the fix, but :)

1. Why isn't the `padding-right` style (https://db.tt/TpjPqm0K) not included in the `hidden-scroll` class as well?

2. It would be better to add the 'hidden-scroll' class to `HTML` tag, not `BODY`. It depends on a page, but if a `BODY` is for example: 
```
body { 
    min-height: 100%; 
    ... 
} 
```
It causes problem in your method (https://db.tt/Jrnq8Y8g). 
Adding the class to `HTML` is more universal solution, because scroll usually is for the whole document, not just for `BODY` element.

**Comment by andreknieriem** [comment]
Hey thx for your answer. The padding right must be calculated by javascript to get the width of the sidebar. I've done it the way bootstrap did it. The class on html-Tag might be better, I will take a look at this. Thanks!

**Comment by bbprojectnet** [comment]
1. You're right. I'm curious - what JS method you use to measure the real scrollbar size in browser?

2. Ok, thanks :)

**Comment by awplige** [comment]
https://github.com/awplige?tab=repositories
