### ISSUE TITLE
Links to SVG images not picked up 

### ISSUE THREAD

**Issue by evolution7-developer** [andreknieriem/simplelightbox#341]
Hi, 

If i use .svg images, they are not being picked up by the event handler to open the light box on click. Is there a way to enable this? 

Thanks. 

V2.14.2

**Comment by Mtillmann** [comment]
have you looked into the `fileExt`-option?

**Comment by evolution7-developer** [comment]
@Mtillmann that was it! Thanks for you help

**Comment by evolution7-developer** [comment]
@Mtillmann that was it! Thanks for you help
