### ISSUE TITLE
Can not close the lightbox preview on iOS

### ISSUE THREAD

**Issue by noezack** [andreknieriem/simplelightbox#35]
Hi, I'm using your Lightbox.
It is beautiful, until I can't close the popup anywhere except close button on iOS only (I don't tried it yet at Windows Phone but Android and iOS.

**Comment by andreknieriem** [comment]
Hi, if you have the option on, the lightbox closes on click outside of the image, eg overlay. Does that not work?

**Comment by andreknieriem** [comment]
Hey anything new about this? Can' reproduce your error.

**Comment by andreknieriem** [comment]
Ok, I close it. Can be reopened if needed.
