### ISSUE TITLE
Lightbox positioning problem!

### ISSUE THREAD

**Issue by themca** [andreknieriem/simplelightbox#36]
Hi!

first of all good work with your simple lightbox, keep it up!

In my case I have a problem with it. The calculation for the .sl-image container (top value) doesn't work properly. In my case the top value is the height of the document, so the container with the image isn't visible! 

Screen -  1: From my inspector
https://www.dropbox.com/s/qc1o0bxgaghbodj/Screenshot%202016-04-07%2007.34.28.png?dl=0
 
Screen - 2 : What the browser window looks like
https://www.dropbox.com/s/zruxy4ai3pzr0vp/Screenshot%202016-04-07%2007.35.42.png?dl=0

There are NO other CSS styles in the document. The HTML is really minimalistic -> https://www.dropbox.com/s/0ckrt7c3lupc7oe/Screenshot%202016-04-07%2007.38.42.png?dl=0

So have you an idea what this issue could cause? 

Regards M.

**Comment by andreknieriem** [comment]
Hi, thats a strange behaviour. Do you have a link for me, hat I can take a look at this?

**Comment by themca** [comment]
it is a simple html file, just unpack it (No viruses or trojans ;) included )
[index.zip](https://github.com/andreknieriem/simplelightbox/files/208006/index.zip)

But you don't have to hurry with it, because i used another lightbox for this project.

Regards M.

**Comment by andreknieriem** [comment]
Ok thanks for that. Really strange problem, will take a look!

**Comment by themca** [comment]
ok :) let me know when you have the solution!

**Comment by andreknieriem** [comment]
Hey found out, that your index.html file is missing the doktype before the opening html tag
http://www.w3schools.com/tags/tag_doctype.asp

If you add it, everything works as aspected. Will take a look, why this is a problem, but this is the best solution for now!

**Comment by themca** [comment]
Lol, really strange indeed...
