### ISSUE TITLE
einzelnes Bild: swipe / drag & opacity Effekt

### ISSUE THREAD

**Issue by olien** [andreknieriem/simplelightbox#37]
Hallo Andre,

ich gucke mir gerade die simplelightbox an und habe zwei Fragen:

**_Edit..._
Beide Fragen haben sich recht schnell geklärt.... Wer lesen kann.. :-)**

Danke für das Plugin!

LG
Oliver

**Comment by olien** [comment]
Ok. Frage 1 hat sich erledigt (animationSlide)

**Comment by andreknieriem** [comment]
Hey, alles klar, super!
