### ISSUE TITLE
Nav button bug with loop false

### ISSUE THREAD

**Issue by pflind** [andreknieriem/simplelightbox#38]
If you have 2 images and set loop to false the next/prev buttons do not act like they should.

Btw, pinch/zoom capabilities on touch devices would be nice addition because lightboxes on especially smartphones aren't that useful when you can't zoom in to see details.

Thanks for sharing!

**Comment by andreknieriem** [comment]
Hey, just fixed the error and fixed some other small issue on loop false feature! New version is online!
