### ISSUE TITLE
Caption Flick onload

### ISSUE THREAD

**Issue by jmbelloteau** [andreknieriem/simplelightbox#39]
Hello,

The problem is when caption position is outside, there is a delay between img load an caption load so it's look like a little flicker. Is it possible to develop caption apparition, a simple fade in could be really nice.

Thanks a lot for you good work

Kind regard

**Comment by andreknieriem** [comment]
Hey,
the delay is fading see line 232
`caption.html(... ...).fadeIn('fast');`
I can't see your problem. Is it because the caption is fading in, after the image fades in?

**Comment by andreknieriem** [comment]
Closed, because I can't reproduce this and no answer. Please reopen if problem still exists
