### ISSUE TITLE
Watermark Option

### ISSUE THREAD

**Issue by jmbelloteau** [andreknieriem/simplelightbox#40]
Hello again,

My goal is to have a div with a back-image class over the image to be abble to add a watermark.
I try very hard to use event to append html code inside lightbox, but it's not working properly.
This is the best solution I've founded... Not really working...

```
 $('.galleries a').on('changed.simplelightbox', function () {
            $('.sl-image').append('<img class="watermark" src="/app/medias/logos/signature.png" alt="Smiley face" height="200" width="200">');
        });
```
The best should be to simply had a div with a class above the caption div directly in the simplelightbox plugin. I'm not good enough in JS to do that, pretty newbie in fact :)

It's a pain in the ass and the quality is never sharp when rendering the watermark directly in the jpg.

Can you help me?

Thank you so much,

Jim

**Comment by andreknieriem** [comment]
Is added to my list and should be easy. Will come soon.

**Comment by andreknieriem** [comment]
Added a div called sl-watermark in my dev code right now. If that is what you wanted, I will release this.

**Comment by andreknieriem** [comment]
New version is online for your watermark html!
