### ISSUE TITLE
Swipe top/bottom to close gallery

### ISSUE THREAD

**Issue by thesergeev** [andreknieriem/simplelightbox#44]
Hello! 
Thank you for the great plugin! That's ideal for my needs.
Is it possible to make swipe top/bottom action to close gallery?

Cheers!

**Comment by andreknieriem** [comment]
Hi, this is a nice idea. I see on how to implement this.

**Comment by andreknieriem** [comment]
Done. Will be in the next version. See http://andreknieriem.de/simple-lightbox-dev/ for demo.

**Comment by andreknieriem** [comment]
New version is online
