### ISSUE TITLE
Caption missing?

### ISSUE THREAD

**Issue by kenw232** [andreknieriem/simplelightbox#45]
I can't figure this out.  Maybe its me. Viewing this page here:
http://rfp.thegreatwaterway.com/planner/facility-view.html?facility_num=767
The first main image there under "Green Acres Inn" does not have a caption.  But its clearly defined with the title="Green Acres Inn" in the HTML source (line 339).  The images below it do have captions though.  Not sure why it won't add the caption for that one.  Line 620 in the HTML source is the jQuery line.  Any clue?

**Comment by andreknieriem** [comment]
Hey, its an  error in your markup. The lightbox looks for title tag on the image, not the Anchor Tag itself.

Take a look at the captionSelecto-Option: Default img "the element where the caption is. Set it to "self" for the A-Tag itself"

In your markuo your image "/includes/show_image.html?facility_num=767&image=featured_image1" has only the title tag at the Anchor not at the image.

**Comment by kenw232** [comment]
Great, that was it.  Thanks for your help.
