### ISSUE TITLE
hello, how to re-init simpleightbox

### ISSUE THREAD

**Issue by liuxc2016** [andreknieriem/simplelightbox#46]
you know , if i use js delete a img nod . lightbox can still see it . how to deal with it？

**Comment by andreknieriem** [comment]
Hey, you can do that by calling destroy and then init it again.

`var gallery = $('.gallery a').simpleLightbox();
gallery.destroy();
gallery = $('.gallery a').simpleLightbox()
`

But it is a good point for a refresh method. I will build it for the next version

**Comment by Raketten1963** [comment]
Will lightbox destroy itself when user click close button, and if not, how to know when to call destroy. I cannot find a ready to destroy event.
I like to close and open my gallery, so I cannot destroy on close....
