### ISSUE TITLE
open.simplelightbox & opened.simplelightbox events are not working

### ISSUE THREAD

**Issue by umairrazzaq** [andreknieriem/simplelightbox#47]
open.simplelightbox & opened.simplelightbox events are not working, but close.simplelightbox & closed.simplelightbox events are working fine as expected. Also I'm not getting any errors/issues on browser console.

**Comment by andreknieriem** [comment]
I will take a look, thanks for telling.

**Comment by umairrazzaq** [comment]
Thanks for the reply :)

**Comment by andreknieriem** [comment]
Hey, ok it's not a bug in the script, it's a bug in the documentation :D The right events are show and shown not open and opened. I will change this in the documentation now.
