### ISSUE TITLE
Add option to hash to the open lightbox for mobile sites

### ISSUE THREAD

**Issue by Siton-Systems** [andreknieriem/simplelightbox#48]
Like this:
http://demos.jquerymobile.com/1.3.0-rc.1/docs/demos/widgets/popup/

Otherwise on Android most of the time the user click on "back" button of the phone to close the modal (like in FB, or google images) - and "by mistake" --> "go back in the url"

**Comment by andreknieriem** [comment]
Hi, this is a nice feature. I take a look, how fast I can implement this

**Comment by andreknieriem** [comment]
One question, do you just want to close the gallery on back button, or do you want to navigate back with the button (load last image for example) The first option is better in my opinion and mostly used.

**Comment by Siton-Systems** [comment]
I want to close :) This is the pattern in android.
