### ISSUE TITLE
Responsive - mobile view - 100% width image?

### ISSUE THREAD

**Issue by Siton-Systems** [andreknieriem/simplelightbox#49]
On mobile the space right - left make the zoom image "to small". How to create image without left-right padding - margin?....

![image](https://cloud.githubusercontent.com/assets/16711871/19421833/b63bd93c-9412-11e6-89c3-fa652f7d6d19.png)

**Comment by andreknieriem** [comment]
Hey,

you could use the widthRatio and heightRatio in the options. 
Like 
`$('a').simpleLightbox({widthRatio : 1, heightRatio :1 })`

**Comment by Siton-Systems** [comment]
Thanks. I will try this

**Comment by andreknieriem** [comment]
Closed for now
