### ISSUE TITLE
Youtube links support

### ISSUE THREAD

**Issue by valentasn** [andreknieriem/simplelightbox#5]
Very nice plugin! One thing is missing do youtube video support in lightbox :) It would be great to have such feature.

**Comment by devariya** [comment]
:+1:  yes , Video support is important not only youtube but also other site and self-hosted video is important .

**Comment by valentasn** [comment]
I agree with @devariya when we can expect to test beta version?

**Comment by andreknieriem** [comment]
Hi @valentasn & @devariya, I don't know if and when I will implement this feature, because this lightbox was created for images and not multimedia/iframe content. I will see what I can do.

**Comment by awplige** [comment]
Hi

## https://github.com/awplige/Gallery-Photo-Gallery

Use Our Plugin

This Should Be Helps You Guys.

Thanks :)

**Comment by login2030** [comment]
From what I found, this is the good plugin for the lightbox, but the video will have to look for something else.
Pechal'ka =(

**Comment by andreknieriem** [comment]
Ok, will never include this, as this is a image lightbox and not for other content. The touch gestures and mobile usage woulb be terrible.
