### ISSUE TITLE
next image not loading when alertError: false

### ISSUE THREAD

**Issue by patrickschoeberlein** [andreknieriem/simplelightbox#52]
not sure if this is intended behaviour or not - but when you hide the errorAlert (with options errorAlert:false) the next image is not loaded when switching from last to first image (or vice versa). To me, it looks like `loadimage()` should be executed even if `options.alertError` is false.

see Line 191 to 199 

` if(options.alertError){
    alert(options.alertErrorMessage);
    if(dir == 1 || dir == -1){
        loadImage(dir);
    } else {
        loadImage(1);
    }
    return;
}`

**Comment by andreknieriem** [comment]
Fixed it. Thanks for your feedback-
