### ISSUE TITLE
Get images from array

### ISSUE THREAD

**Issue by apmartins** [andreknieriem/simplelightbox#53]
Is it possible to load the images from an array?

I have a situation where I don't want all the images on the page, all I need is to click a link and open simplelightbox with the gallery.

**Comment by andreknieriem** [comment]
Hey @apmartins,

you can do this, by adding all the images to your html and put them into a container which is display:none. In the example below it's called "your-gallery". The button with class ".open-gallery" then just opens the gallery.

On this page, it is done this way and as you see, if you click "Galerie öffnen" The lightbox appears:
https://www.heuking.de/de/ueber-uns/standorte/kanzlei/duesseldorf.html

The javascript code looks like this:
```javascript
var gallery = $('.your-gallery a').simpleLightbox();
			
$('.open-gallery').click(function(e){
	e.preventDefault();
	gallery.open($('.your-gallery a:first'));
});
```

**Comment by bacloud22** [comment]
Such a beautiful library should have this option out of the box. Really this is to be expected out of the box. Source as an array is just natural?. thanks
