### ISSUE TITLE
Lightbox doesn't work with images with parameters.

### ISSUE THREAD

**Issue by Juuro** [andreknieriem/simplelightbox#59]
Hi Andre!

Thank you for this great lightbox! :-)

Sadly I noticed that your lightbox won't work with image URL that have parameters attached. For example:

`<a class="example-image-link" href="images/image-1.jpg?moep=doep" data-lightbox="example-1"><img class="example-image" src="images/thumb-1.jpg" alt="Girl looking out people on beach"></a>`

With this link there won't open the lightbox but the image directly. I found out, that this has something to do with the file extension check. When I set `fileExt: false` it works. I suppose it doesn't do anything with the URL at all. But it would be nice if we could have params AND the file extension check.

Best regards, Sebastian

**Comment by andreknieriem** [comment]
Hi Sebastian,

I will take a look on how to do this the right way. Thanks for the improvement.

Best regards, André

**Comment by andreknieriem** [comment]
So this feature will be added in the next version. I have time now to improve the lightbox.

**Comment by andreknieriem** [comment]
Just added the feature.
