### ISSUE TITLE
Issue displaying the last image from gallery

### ISSUE THREAD

**Issue by chidalgom1503** [andreknieriem/simplelightbox#63]
Hi andre, great plugin!

This issue occurs on this gallery I 'been working

for  example:
[https://jsfiddle.net/chidalgom/wLf8rd6q/15/](https://jsfiddle.net/chidalgom/wLf8rd6q/15/)

if you click on any image in the gallery (not the last of course), will open the lighbox normally, but try to navigate to the last image... it will jump from the penultimate image to the first, and only works if you navigate from the first image to last (backwards).

beside this problem I think this is a very helpfull and clean plugin.
Like it very much.

many thanks!

**Comment by andreknieriem** [comment]
Hi there. You are using an very old version of simplelightbox.js

If you compare your source:
https://www.jqueryscript.net/demo/Responsive-Touch-enabled-jQuery-Image-Lightbox-Plugin/dist/simple-lightbox.min.js

with the current source:
https://raw.githubusercontent.com/andreknieriem/simplelightbox/master/dist/simple-lightbox.min.js

you see the big difference. Please use latest version, maybe from cdnjs 
https://cdnjs.cloudflare.com/ajax/libs/simplelightbox/1.10.5/simple-lightbox.min.js

**Comment by chidalgom1503** [comment]
I see... will trying the new versión.

Thanks for your help
