### ISSUE TITLE
Go to next image on image click

### ISSUE THREAD

**Issue by darklow** [andreknieriem/simplelightbox#64]
Is there a way to go to next image when clicking on the image?
Any workarounds using events maybe?
Thank you

**Comment by andreknieriem** [comment]
Yes, you can do something like:

`
var gal = $('.gal a').simpleLightbox();
$('.sl-image img').click(function(e){
  e.preventDefault();
  // trigger next image
  gal.next();
});
`
It's not testet but I think this works
