### ISSUE TITLE
Image bse64

### ISSUE THREAD

**Issue by Szymon-dziewonski** [andreknieriem/simplelightbox#66]
Hello, I noticed that if you use base64 image , then gallery doesnt work as it does not discover it as valid url so I removed this lines and everything is working. Im writing this as I think it should be fixed in plugin itself :)

Starts on line 484 /simple-lightbox.js file
```
objects.on( 'click.'+prefix, function( e ){

		if(isValidLink(this)){  //REMOVED

			e.preventDefault();
			if(animating) return false;
			openImage($(this));

		}    //REMOVED

});
```

Thank you for plugin, best if you'd ask me:)
Cheers

**Comment by andreknieriem** [comment]
Hi thanks, but you can just set fileExt to false. See docs.

**Comment by Szymon-dziewonski** [comment]
yep thats true, but still data image base64 are correct paths, that option is unusual, anyway thank you

**Comment by andreknieriem** [comment]
Hm the check checks only, if your file extension is valid, so that the plugin doesn't open an .mov Url. It doesn't check, if given URL is an image.
