### ISSUE TITLE
Help needed, lightbox modal not coming up

### ISSUE THREAD

**Issue by EmmanuelOloke** [andreknieriem/simplelightbox#67]
Hi Andre, I'm a newbie to JS and I just came across your plugin, nice work by the way. I've written and included all the necessary code/files, don't know if I'm missing anything though. The lightbox doesn't come up when I click on an image, the image just loads fully in the window instead. Your prompt reply will be highly appreciated, thanks.

**Comment by thakurpunk** [comment]
Hi @EmmanuelOloke, just for info, could you please check if you have correctly called the js file and using jquery.min.js within your doc. Please let me know if you have already did.

**Comment by EmmanuelOloke** [comment]
Thanks for your response @thakurpunk, yes I have called the js file (simple-lightbox.js) and also included the jquery library (https://ajax.googleapis.com/ajax/libs/jquery/2.2.4/jquery.min.js), I'm obviously missing something or not doing something right

**Comment by thakurpunk** [comment]
Alright, please visit this link, http://shoreline.stagingdevsite.com/#gallery i have used the plugin in my gallery section, may be you can get any idea. Or please share any codepen or fiddle of your code so that I can check your code.

**Comment by EmmanuelOloke** [comment]
Alright, I'll get back to you ASAP. Thanks for your help so far.

**Comment by andreknieriem** [comment]
So no answer. I will close this.
