### ISSUE TITLE
Bootstrap compatibility

### ISSUE THREAD

**Issue by Wintermute79** [andreknieriem/simplelightbox#69]
Bootstrap 3.3.7 fixed nav bar has a z-index of 1030, .sl-overlay has 1006 so it's always above the gallery.
Slightly increasing the z-indexes in the CSS would make Simplelightbox out-of-the-box compatible with Bootstrap.

See Bootstrap CSS at
https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.7/css/bootstrap.css

**Comment by andreknieriem** [comment]
That's a good point. Thanks for it!

**Comment by andreknieriem** [comment]
Done in new version 1.10.7

**Comment by Wintermute79** [comment]
Wow! That was really quick! Thank you!
