### ISSUE TITLE
File extension limitation

### ISSUE THREAD

**Issue by mynamesleon** [andreknieriem/simplelightbox#7]
Your `isValidLink` function limits the types of images that can be used - so if someone wants to use a url that doesn't include a file extension (e.g. http://placehold.it/500x500), or one that doesn't have one of the allowed extensions, or if the url includes query parameters after the file extension, then the lightbox won't work.

It might be worth either: removing this and trusting in the developer integrating it that they'll use an image, or just adding a small note to the readme about this limitation.

**Comment by andreknieriem** [comment]
Hey leon. Thanks for the advice. I will change that option, that you can say false or a regexp. Will be in the next version.

**Comment by andreknieriem** [comment]
Hey Leon, the new version is online.
