### ISSUE TITLE
Load images from data attribute

### ISSUE THREAD

**Issue by slavanga** [andreknieriem/simplelightbox#70]
Sometimes the `href` attribute doesn’t contain the lightbox image.
Can we add a setting to define the source attribute?

```html
<a href="some-image.jpg" data-src="image-for-popup.jpg">Open image</a>
```

**Comment by andreknieriem** [comment]
Good idea and easy to implement.

**Comment by arthursoares** [comment]
That would be nice :)

**Comment by andreknieriem** [comment]
Done.
