### ISSUE TITLE
simplelightbox broken with Chromium 60

### ISSUE THREAD

**Issue by midzer** [andreknieriem/simplelightbox#72]
Hi all,
with Chromium 60 development version simplelightbox is broken for me:
After click on an image loading spinner appears but lightbox is not shown. Furthermore console shows an error for jquery 3.2.1 in CSP directive which i temporarily resolved by adding "unsafe-inline" to .htaccess file. Using Chromium stable version 58 lightbox works flawlessly.

You can find sample library at https://feuerwehr-eisolzried.de/media/

Cheers and have a nice day
midzer

**Comment by andreknieriem** [comment]
Hi, I can't test an chromium beta version. Maybe you reopen this task, if it's still broken in stable version 59 or 60. Sorry.
