### ISSUE TITLE
Support launching lighbox by clicking on any element

### ISSUE THREAD

**Issue by adarshu** [andreknieriem/simplelightbox#73]
I noticed that this works fine:
`var lightbox = $('.gallery a').simpleLightbox(options);`

But if I do something like below, with the sourceAttr set to "data-pic-link", clicking on the table row doesn't launch lightbox:
`var lightbox = $('.myrow').simpleLightbox(options);`

A row looks like:
`<tr class="myrow" data-pic-link="http://example.com/mypic.jpg">....</tr>`

Any reason why?

Thanks! Love this plugin! Very nice!

**Comment by andreknieriem** [comment]
Hi, your Code is cutted out. Can you post it on jsfiddle, or somewhere else?

**Comment by adarshu** [comment]
Hi Andre,
Here it is:
<tr class="myrow" data-pic-link="http://example.com/mypic.jpg">....</tr>
With the above, this doesn't seem to work when the row is clicked:
var lightbox = $('.myrow').simpleLightbox(options);
Does the container have to be an <a> tag?
Thanks!

**Comment by adarshu** [comment]
Any update andre? Please let me know if this is possible.

**Comment by andreknieriem** [comment]
It's not possible at this moment, maybe I will try to get this work with the next version.

**Comment by XzenTorXz** [comment]
I use this workaround, to prevent preloading to much:

```
$(document).on('click', '.gallery a', function(e){
    e.preventDefault();
    var $items =  $(this).parents('.gallery:first').find('a'); //optional: only get images within the clicked gallery or use $(this)
    var startItem = $(e.target).parents('a:first'); //get the clicked element
    $items.simpleLightbox().open(startItem);
});
```

this might also work for your use case.

**Comment by andreknieriem** [comment]
See @XzenTorXz example. This works good
