### ISSUE TITLE
Support closing lightbox before image loads

### ISSUE THREAD

**Issue by adarshu** [andreknieriem/simplelightbox#74]
Hi, first off, I love this plugin! Lots of features but easy to use.

One issue I'm facing is that on click of an image (thumbnail), the lightbox loads the full image, which can be slow and take 10 seconds. During this time, the close button doesn't work on clicking it. I see in your code that if `isAnimated` is true, `close `just returns.

Is there a workaround? Would be good to let users close image lightboxes for images that are slow to load so they can load another image.

Thanks!

**Comment by andreknieriem** [comment]
good point, will be in the next version.

**Comment by andreknieriem** [comment]
* Fixed in new version v1.15.0
