### ISSUE TITLE
Adding image to exist lightbox

### ISSUE THREAD

**Issue by alexander-schranz** [andreknieriem/simplelightbox#77]
I'm searching for a solution to add an image to an exist lightbox.

E.g.:

```js
$('#image1').simpleLightBox({ group: 'test' });
$('#image2').simpleLightBox({ group: 'test' }); // this image should be added to the exist lightbox (test) so you can slide also to this image.
```

or

```js
var lightBox = $('#image1').simpleLightBox({ group: 'test' });
lightBox.add($('#image2')); // this image should be added to the exist lightbox (test) so you can slide also to this image.
```

**Comment by andreknieriem** [comment]
Hi, there is a method named "refresh" which can do what you need:
refresh | Destroys and reinitilized the lightbox, needed for eg. Ajax Calls, or after dom manipulations

var gallery = $('.gallery a').simpleLightbox();

gallery.refresh(); // Refresh

Best regards Andre

**Comment by alexander-schranz** [comment]
Doesn't match my use case as I want to avoid to parse the whole DOM again for the elements. I have the element and just want to add it to an exist gallery without reinit them.

**Comment by andreknieriem** [comment]
Alright I understand. I think I can built such a feature in.
