### ISSUE TITLE
Opening gallery on button click

### ISSUE THREAD

**Issue by tekblupace** [andreknieriem/simplelightbox#78]
Hey, 

So im just wondering if I would be able to open a gallery on a button click.
I dont want the gallery to be seen on the page, only in the lightbox when a button is clicked.

Is this possible?

Regards,

Pace

**Comment by andreknieriem** [comment]
Yes that's pretty easy. You can see a working example on this page.
http://www.gartenvillen-oyten.de/
Just click the red link on the header.

What you have to do is the following:
- Create a div and put links in it with the href to your big images and set that div to display none
- Add a JS like this:

```var lightbox= $('.your-div a').simpleLightbox();

	$('.yourbutton').click(function(e){
		e.preventDefault();
		lightbox.open($('.your-div a:first'));
	});
```

**Comment by tekblupace** [comment]
Hi,

So i have my div with a test image in there:

<div id="gallery">
        <a href="img/splash/header.jpg">my image</a>      
    </div>

An i have set this to display none through css

#gallery{
    display: none;
}


I have my button
  <a class="btn btn-quick btn-fashion text-right animated slideInRight" id="test" href="#fashion" role="button" title="fashion">Fashion</a>

I have added the script to my head

<script>$('#test').click(function(e){
		e.preventDefault();
		lightbox.open($('#gallery a:first'));
    });</script>


However I still can’t get this to work, any help appreciated, Im only just getting to grips with bootstrap and its a steep learning curve for me.


Kind regards


Pace

**Comment by andreknieriem** [comment]
You haven't initialized the lightbox yet. 
This has to be the first call.
```
var lightbox = $('#gallery a').simpleLightbox();
```

**Comment by tekblupace** [comment]
Hey, so I still cannot get this to work.


<script>
    var lightbox = $('#gallery a').simpleLightbox();

    $('#test-me').click(function(e) {
        e.preventDefault();
        lightbox.open($('#gallery a:first'));
    });

</script>


<a class="btn btn-quick btn-fashion text-right animated slideInRight" href="#" id="test-me" role="button" title="fashion">Fashion</a>
                                <br>


 <div id="gallery">
                <a href="img/splash/header.jpg">my image</a>
            </div>

**Comment by tekblupace** [comment]
Hi, so this is the error I am getting 

TypeError: $('.gallery a').simpleLightbox is not a function. (In '$('.gallery a').simpleLightbox()', '$('.gallery a').simpleLightbox' is undefined)

my site is here dev.blupace.com

Any help in getting this to would would be really appreciated.

Kindest of regards,


Pace

**Comment by tekblupace** [comment]
Hey, 

So i got the issue resolved… 
My custom JS was after the loading of simplelightbox :-S

**Comment by andreknieriem** [comment]
Alright!
