### ISSUE TITLE
pinch/zoom capability on touch devices

### ISSUE THREAD

**Issue by sashtown** [andreknieriem/simplelightbox#79]
Hey André, first of all thanks for that nice lil' lightbox! I might be missing something but is there a way to make pinch/zoom working on touch devices? That would be very helpful imho. Thanks in advance!

**Comment by andreknieriem** [comment]
A nice feature request, but not easy to implement. Will try to take a look at this!

**Comment by perfectoweb** [comment]
Yes, it's important feature, because more pictures in mobile devices is very small, and users want to zoom it with double click or resize with 2 fingers.

**Comment by andreknieriem** [comment]
That's right, but it makes the code and everything from a lot larger and I must take a look if I can it to work on every browser.

**Comment by sashtown** [comment]
@andreknieriem Jep, gotcha. But I think this feature for mobile UX is way too important not to implement. I personally would accept the more of code anytime while having that UX-boost. It would make the lightbox (nearly) perfect to integrate and use imho. I'd be a no-brainer and in terms of modern and well maintained lightboxes that's really hard to find out there atm.

**Comment by perfectoweb** [comment]
Yes, @sashtown is right. It’s very important for mobile UX. I’m look for analytics and users action in my website, and more users try to zoom picture with two finger or double tap.. maybe you can disable restriction to default browser zooming?

**Comment by sashtown** [comment]
Hi @andreknieriem! Any news on this so far? 😎

**Comment by webchun** [comment]
Looking forward for this too :)

**Comment by perfectoweb** [comment]
I’m wait too)

**Comment by connect-technologies** [comment]
+1

**Comment by artmaug** [comment]
+1

**Comment by ahmadzissa** [comment]
+1 we really need this feature

**Comment by andreknieriem** [comment]
Started today. Pretty hard to built. Updates are Comic.

**Comment by harry369** [comment]
Hey @andreknieriem, looking forward for pinch/zoom updates.

**Comment by yortem** [comment]
+1

**Comment by andreknieriem** [comment]
Hey, progress can be found here. It is not that easy and nearly doubles the complete source-code.
https://www.andrerinas.de/simplelightbox-pinch/demo/index.html

**Comment by ahmadzissa** [comment]
I tested it on my phone and it's really amazing even if it makes the size larger.   but keep resetting to initial position when you move the zoomed image  anyway we will be waiting for final results. Thank you for the hard work

**Comment by andreknieriem** [comment]
Sure. It is still in progress. Can anyone test it with an iphone? I think it's working now.

**Comment by andreknieriem** [comment]
Gone live. Have fun!

**Comment by sashtown** [comment]
This is great! It works perfectly fine in Mobile Safari on iPhone 8 and iPad Pro 11". And the weight is still more than acceptable imho. Thanks for taking the time to work on this!

**Comment by joffreymahieu** [comment]
Hi,
I just updated my SimpleLightbox to make use of pinch to zoom. It works on chrome, but it doesn't on safari. I'm using an iPad Air and iPhone X. Do I have to change something extra to make it work for safari?
