### ISSUE TITLE
Disable "Right Mouse Klick"

### ISSUE THREAD

**Issue by ausgedacht** [andreknieriem/simplelightbox#8]
Wäre super, wenn die einstellbar wäre. Um den klau von Bildmaterialien zu erschweren. :) 

Super Sache deine Simple Lightbox!

**Comment by andreknieriem** [comment]
Hallo, danke für dein Feedback! Ich werde in die nächste Version als Option einbauen ;)

**Comment by andreknieriem** [comment]
Ist im Sourcecode implementiert und demnächst dabei!

**Comment by ausgedacht** [comment]
Super Sache! Super Support! Werd deine Lightbox weiterempfehlen!
Vielen Dank
