### ISSUE TITLE
Wrong top value in mobile safari after top address bar and bottom dock is hidden

### ISSUE THREAD

**Issue by eric-tiew93** [andreknieriem/simplelightbox#83]
Hi. Theres an issue with the top calculation when the top address bar and the bottom dock is hidden in mobile safari which causes a change in window.innerheight instead of window height. I suggest changing the top calculation to this:

$('.sl-image').css({
     'top':    ( window.innerHeight - imageHeight ) / 2 + 'px',
     'left':   ( $( window ).width() - imageWidth - globalScrollbarwidth)/ 2 + 'px'
});

Thanks and good job on the light box!

**Comment by andreknieriem** [comment]
Hi thanks for your feedback. Will take a look if innerHeight will work and not break other settings.

**Comment by andreknieriem** [comment]
OK testet it. It is only nice working in mobile safari. You can see very much code and understanding what is going on. https://stackoverflow.com/questions/14388367/mobile-safari-window-height-url-bar-discrepancy I will try to get something to work with that link.

**Comment by andreknieriem** [comment]
Sorry. I will reopen this, if this is still a problem.
