### ISSUE TITLE
refresh() is not working

### ISSUE THREAD

**Issue by jotrk** [andreknieriem/simplelightbox#86]
Hi,

I'm inserting some elements in my DOM with ajax. I use the `when()` callback for the async stuff to return and then call refresh() on a lightbox instance in a closure. However, the newly added pictures don't open the lightbox. If I call `destroy()` and reassign `lightbox = $(..).simpleLightbox();` it works.

**Comment by andreknieriem** [comment]
Hi, are you sure it doesn't work? 
´´´
this.refresh = function(){
  this.destroy();
  $(this).simpleLightbox(options);
};
´´´

if exactly the thing you do.

**Comment by jotrk** [comment]
I know, I also looked at the code and I found it confusing. But that's what I saw. Unfortunately I can't test it anymore, because I was evaluating lightboxes and settled for something else.

**Comment by andreknieriem** [comment]
Ok. Cannot reproduce then
