### ISSUE TITLE
Click to close does not work properly after instantiation

### ISSUE THREAD

**Issue by jotrk** [andreknieriem/simplelightbox#87]
Hi,

When I click on an image in the lightbox the lightbox will only close if I move the mouse a little (up- or downwards). This happens only on a fresh instance of lightbox, e.g. newly loaded page. On the second time and so on, it works with a single click without moving the mouse.

**Comment by andreknieriem** [comment]
Closing if swiping is a feature. The second time and so on were errors ( swipeDiff and swipeDiffY get wrong values if not swiping) Now it does only close on swipe.
