### ISSUE TITLE
Want to use "rel" option.

### ISSUE THREAD

**Issue by iwabuchi** [andreknieriem/simplelightbox#89]
Hi. I like this plugin!
I want to use the "rel" option. 
Because I want to group images using the same class name.
But, It seems to stop working if "rel" option is set to "true".:sweat_smile:
Still  I can't understand.:hushed:
Could you tell me how to use it?
I wrote like this↓↓↓（The image path is omitted）

```
$(function(){
  if ($('.js_lightBox').length) {
    var simpleL = {
    rel:  'true',
  }
  $('.js_lightBox').simpleLightbox( simpleL );
  }
})

```
```
<ul>
  <li>
    <a href="" class="js_lightBox" rel='lightbox-1'>
      <img src="">
    </a>
  </li>
  <li>
    <a href="" class="js_lightBox" rel='lightbox-1'>
      <img src="">
    </a>
  </li>
</ul>


<ul>
  <li>
    <a href="" class="js_lightBox" rel='lightbox-2'>
      <img src="">
    </a>
  </li>
  <li>
    <a href="" class="js_lightBox" rel='lightbox-2'>
      <img src="">
    </a>
  </li>
</ul>
```

**Comment by andreknieriem** [comment]
Hi, yeah there was a bug with it and jquery 3+, but how you use it, it's wrong. You have to do it like this:

 var lb1 = $('.js_lightBox').simpleLightbox( {rel: 'lightbox-1'} );
 var lb2 = $('.js_lightBox').simpleLightbox( {rel: 'lightbox-2'});

**Comment by dslpp056193** [comment]
Really? So, why that need, if at the end you also need set the images groups inside javascript?
I think that grouping should works at html side, like in issue "wrong" example.
If i have a static gallery i can do it in js and without your script's grouping. But where you saw static gallery with separating by groups?

**Comment by sashtown** [comment]
@andreknieriem Hey Andre! Wouldn't it be helpful if 

```js
rel: true
```

would just automatically check for the `rel` attribute of the current element and group images based on that? There might be a whole bunch of use cases in which you don't know the value of the attribute and its gallery yet (e.g. modular content pages with multiple gallery modules, editorially clicked (and named) via a CMS).

**Comment by andreknieriem** [comment]
This is true. I am just in the end for the v2.0.0 with no jQuery dependency. Will be out soon. After that, I will make the rel better.
