### ISSUE TITLE
Android image loading bug

### ISSUE THREAD

**Issue by stratboy** [andreknieriem/simplelightbox#90]
Hi, thank you for this code. I think there could be a bug at least on Android browser, under Android 4.4.2. If I visit your home page with my smartphone, and start to swipe, there will be soon alerts saying that image was not found and that the next one will be loaded. Also image loading is quite slow. But this doesn't happen on standard desktop browser, where your plugin is super smooth.

**Comment by andreknieriem** [comment]
Hi that is not a bug. The images are to big. I will decrease the size. The alert is a feature, to show, that the lightbox sees that an image is missing an can skip it or display an error.
