### ISSUE TITLE
Animation slide option question/suggestion

### ISSUE THREAD

**Issue by vripak** [andreknieriem/simplelightbox#91]
Hello, 
Excuse me if this is not the right place to post this but I have a question about if it is possible change how the animation works. First off though I have say that Simple Lightbox is incredible in its responsiveness in desktop and mobile, its clean aesthetic, and easy implementation. The only thing that I feel like lacking is the transition from one image to the next. The fade causes too much of a disturbing flicker while going through the gallery...would it be possible to implement (or maybe this is an option that I haven't found) a way to smoothly transition, without using a fade, by dragging to reveal the next image? In short, I am wondering if it is possible to have a similar transition effect as with Flickity?

**Comment by andreknieriem** [comment]
Hi, thats not easy to implement, because there is only 1 visible image. In a carousel like flickity or slick, you have all images in one row and move them. Maybe you can set down the animation speed to load images faster.

**Comment by vripak** [comment]
Ah okay. Thank you for the response.
