### ISSUE TITLE
Full width/height image

### ISSUE THREAD

**Issue by Guduche** [andreknieriem/simplelightbox#93]
Hi, firstly, thank you for this really good lightbox ! Is it possible to make the buttons (close, next and previous) appear above the image ? I want the images to appear in full width or height but the buttons appear behind the image.

**Comment by andreknieriem** [comment]
Sure. Just edit the z-index for the buttons. Now .sl-image (the image itself) has z-index: 10000 and the navigation/close buttons have z-index 1060. The higher the index, the more to the front. So change z-index to 10001 for buttons would help.

**Comment by Guduche** [comment]
Thank you !
