### ISSUE TITLE
Using caption as a link - problem with touch

### ISSUE THREAD

**Issue by treacle0996** [andreknieriem/simplelightbox#94]
Thank you for this lightbox! So easy to customise. 

Only issue I have is I am using 	captionType: 'data', and in the data-title I am using <a href='..>
Works fine with a mouse, but link does not work on touch.

Am I missing something??

Thanks

**Comment by andreknieriem** [comment]
Yeah you are right. It is because the caption is inside the touch/moveable area and the touch event steals the click event. I can try to fix this.

**Comment by treacle0996** [comment]
Thanks for the reply.
I've been trying to come up with a workaround - by moving the sl-caption outside of sl-image using:
```
.on('shown.simplelightbox', function(e){
 var myCaption = $('.sl-caption');
...
 myCaption.parent().after(myCaption);
```
The link then works ok, but I just can't get the positioning right. I'm grabbing the initial left & top position of sl-caption and then re-applying it once its moved, but results are little random..
I don't suppose you have a quick fix do you?

Thanks.

**Comment by andreknieriem** [comment]
No sorry. But I think you can get the widht and heigh of the image and the position and calc this together. $('.sl-image').width(), $('.sl-image').height() and $('.sl-image').pos(). Hope it helps
